/* ============================================================
   DASAR · Deducciones autonómicas del IRPF
   Datos extraídos de los TEXTOS CONSOLIDADOS oficiales (BOE y
   portales forales). Revisar y actualizar cada ejercicio.
   Campos: n=nombre · imp=% o importe · lim=límite · renta=requisito
   de renta · req=otros requisitos · art=artículo
   ============================================================ */
window.DASAR_DED = {

  madrid: {
    norma: "Decreto Legislativo 1/2010 (TR tributos cedidos)",
    id: "BOCM-m-2010-90068",
    url: "https://www.boe.es/buscar/act.php?id=BOCM-m-2010-90068",
    act: "29/12/2025",
    nota: "Los límites de renta generales están en el art. 18: en muchas deducciones, base imponible de la unidad familiar ≤ 30.930 € × nº de miembros.",
    items: [
      { n: "Nacimiento o adopción de hijos", imp: "721,70 € por hijo (el ejercicio y los 2 siguientes); +721,70 € por hijo en parto múltiple el 1.er año", lim: "—", renta: "BI ≤ 30.930 / 37.322,20 €; suma BI unidad familiar ≤ 61.860 €", req: "Convivencia; prorrateo; hijos nacidos/adoptados desde 1-1-2023", art: "4" },
      { n: "Adopción internacional de niños", imp: "721,70 € por hijo (+50 % si convive con ambos adoptantes)", lim: "—", renta: "No se establece", req: "Compatible con la del art. 4", art: "5" },
      { n: "Acogimiento familiar de menores", imp: "618,60 € (1.º) / 773,25 € (2.º) / 927,90 € (3.º y sucesivos)", lim: "—", renta: "BI ≤ 26.414,22 / 37.322,20 €", req: "Convivencia > 183 días; certificado de la Consejería", art: "6" },
      { n: "Acogimiento no remunerado de mayores de 65 años y/o con discapacidad", imp: "1.546,50 € por persona", lim: "—", renta: "BI ≤ 26.414,22 / 37.322,20 €", req: "Discapacidad ≥33 % o >65 años; >183 días; sin ayudas de la CM; sin parentesco ≤4.º grado", art: "7" },
      { n: "Cuidado de ascendientes", imp: "515,50 € por ascendiente", lim: "—", renta: "No se establece", req: "Ascendiente >65 años o con discapacidad que genere el mínimo; prorrateo", art: "7 bis" },
      { n: "Arrendamiento de vivienda habitual", imp: "30 %", lim: "1.237,20 €", renta: "BI ≤ 26.414,22 / 37.322,20 €; suma unidad familiar ≤ 61.860 €", req: "Menores de 40 años; el alquiler debe superar el 20 % de la BI; resguardo de fianza", art: "8" },
      { n: "Gastos del arrendador de viviendas", imp: "10 %", lim: "154,65 €/año", renta: "No se establece", req: "Conservación, contratos, seguros, certificados energéticos", art: "8 bis" },
      { n: "Arrendamiento de viviendas vacías", imp: "1.000 € por inmueble", lim: "Máx. 5 inmuebles", renta: "No se establece", req: "Vivienda vacía ≥1 año; contrato ≥3 años; arrendatario no pariente ≤3.er grado", art: "8 ter" },
      { n: "Donativos a fundaciones y clubes deportivos", imp: "15 %", lim: "Base ≤10 % de la base liquidable", renta: "No se establece", req: "Fundaciones inscritas en el Registro de la CM; clubes deportivos elementales/básicos", art: "9" },
      { n: "Incremento del coste de la financiación de la vivienda habitual (subida de tipos)", imp: "25 % del exceso de intereses sobre el euríbor de dic-2022", lim: "300 €/año", renta: "Art. 18.2 (30.930 € × nº miembros)", req: "Hipoteca a tipo variable anterior; precio de adquisición ≤390.000 €; incompatible con art. 12", art: "10" },
      { n: "Cambio de residencia a municipio en riesgo de despoblación", imp: "1.000 € (el ejercicio del traslado y el siguiente)", lim: "—", renta: "Art. 18.2", req: "Menores de 35 años; municipio <2.500 hab.; mantener residencia 3 años más", art: "10 bis" },
      { n: "Adquisición de vivienda habitual en municipios en riesgo de despoblación", imp: "10 % del precio, prorrateado en 10 años", lim: "1.546,50 €/año", renta: "Art. 18.2", req: "Menores de 35 años; municipio <2.500 hab.; mantener residencia 3 años", art: "10 ter" },
      { n: "Gastos educativos", imp: "15 % escolaridad e idiomas; 5 % vestuario escolar", lim: "412,40 €/hijo; 927,90 € con escolaridad; 1.031 € si 1.er ciclo de Infantil", renta: "Art. 18.2", req: "Hijos que generen el mínimo; se minora por becas", art: "11" },
      { n: "Cuidado de hijos <3 años, mayores dependientes y personas con discapacidad", imp: "25 % de las cuotas de empleados de hogar (40 % si familia numerosa)", lim: "463,95 €/año (618,60 € familia numerosa)", renta: "Art. 18.2", req: "Alta como empleador; ≥40 h mensuales; actividad ≥183 días", art: "11 bis" },
      { n: "Intereses de préstamos para vivienda de jóvenes <30 años", imp: "25 % de los intereses", lim: "1.031 €/año", renta: "No se establece", req: "Hipoteca para vivienda habitual; hasta el mes anterior a cumplir 30", art: "12" },
      { n: "Intereses de préstamos para estudios de Grado, Máster y Doctorado", imp: "Importe de los intereses", lim: "—", renta: "No se establece", req: "Préstamo de entidad de crédito; contribuyente, cónyuge o descendientes", art: "12 bis" },
      { n: "Estudios cursados por jóvenes <30 años empleados", imp: "50 % de la matrícula", lim: "400 €", renta: "No se establece", req: "Alta en SS ≥300 días; Grado o FP superior; curso completo", art: "12 ter" },
      { n: "Adquisición de vivienda habitual por nacimiento o adopción", imp: "10 % del precio, prorrateado en 10 años", lim: "1.546,50 €/año", renta: "Art. 18.2", req: "Compra en los 3 años siguientes al nacimiento; habitar 12 meses y ≥3 años", art: "13" },
      { n: "Obtención de la condición de familia numerosa", imp: "50 % de la cuota íntegra autonómica (general) / 100 % (especial)", lim: "General 6.186 / 12.372 €; especial 12.372 / 24.744 €", renta: "Art. 18.2", req: "Ejercicio del reconocimiento y los 2 siguientes", art: "13 bis" },
      { n: "Familias con dos o más descendientes e ingresos reducidos", imp: "10 % de la cuota íntegra autonómica minorada", lim: "—", renta: "Suma de BI (contribuyentes + descendientes) ≤ 24.744 €", req: "Dos o más descendientes que generen el mínimo", art: "14" },
      { n: "Inversión en entidades nuevas o de reciente creación", imp: "40 % (50 % si participadas por universidades/centros de investigación, SAL/SLL y cooperativas)", lim: "9.279 €/año (12.372 € en el 50 %)", renta: "No se establece", req: "≤40 % del capital; mantener 3 años; domicilio en la CM, actividad y empleo", art: "15" },
      { n: "Fomento del autoempleo de jóvenes <35 años", imp: "1.031 €", lim: "—", renta: "No se establece", req: "Primera alta en el Censo de Empresarios; actividad en la CM; ≥1 año", art: "16" },
      { n: "Inversión en entidades cotizadas en el MAB", imp: "20 %", lim: "10.310 €", renta: "No se establece", req: "Mantener 2 años; ≤10 % del capital; domicilio en la CM; incompatible con art. 15", art: "17" },
      { n: "Inversiones de nuevos contribuyentes procedentes del extranjero", imp: "20 % del valor de adquisición de valores", lim: "—", renta: "No se establece", req: "No residente los 5 años previos; mantener 6 años; ≤40 % y sin funciones ejecutivas; desde 1-1-2024", art: "17 bis" }
    ]
  },

  cataluna: {
    norma: "Decreto Legislativo 1/2024 (libro sexto del Código tributario de Catalunya)",
    id: "BOE-A-2024-6951",
    url: "https://www.boe.es/buscar/act.php?id=BOE-A-2024-6951",
    act: "25/03/2026",
    items: [
      { n: "Nacimiento, adopción o acogimiento", imp: "300 € (conjunta) / 150 € cada progenitor (individual) / 300 € (monoparental)", lim: "—", renta: "No se establece", req: "Mismo importe en acogimiento; adopción incompatible con acogimiento", art: "612-1" },
      { n: "Contribuyentes que queden viudos", imp: "150 € (300 € con descendientes que computen para el mínimo)", lim: "—", renta: "No se establece", req: "El ejercicio de la viudedad y los 2 siguientes", art: "612-2" },
      { n: "Alquiler de la vivienda habitual", imp: "10 %", lim: "500 € (1.000 € si familia numerosa o monoparental)", renta: "BI general + ahorro menos mínimo personal y familiar ≤ 30.000 / 45.000 €", req: "≤35 años, o paro ≥183 días, o discapacidad ≥65 %, o viudo/a ≥65 años; identificar NIF del arrendador", art: "612-3" },
      { n: "Rehabilitación de la vivienda habitual", imp: "1,5 %", lim: "Base máx. 9.040 €/año", renta: "No se establece", req: "Vivienda que sea o vaya a ser la habitual", art: "612-4" },
      { n: "Intereses de préstamos para máster y doctorado", imp: "Importe de los intereses", lim: "—", renta: "No se establece", req: "Préstamos concedidos a través de la AGAUR", art: "612-5" },
      { n: "Donaciones a entidades de fomento del catalán o del occitano", imp: "15 %", lim: "10 % de la cuota íntegra autonómica", renta: "No se establece", req: "Entidades del censo de política lingüística (IEC, Institut d'Estudis Aranesi…)", art: "612-6" },
      { n: "Donaciones a investigación científica y desarrollo e innovación tecnológicos", imp: "30 %", lim: "10 % de la cuota íntegra autonómica", renta: "No se establece", req: "Universidades y centros de investigación catalanes; suma con la estatal ≤100 %", art: "612-7" },
      { n: "Donaciones para el medio ambiente, patrimonio natural y custodia del territorio", imp: "15 %", lim: "5 % de la cuota íntegra autonómica", renta: "No se establece", req: "Entidades del censo de entidades ambientales", art: "612-8" },
      { n: "Inversión de un ángel inversor en entidades nuevas o de creación reciente", imp: "40 % (50 % si participadas por universidades o centros de investigación)", lim: "12.000 €", renta: "No se establece", req: "≤35 % del capital; domicilio en Cataluña; ≥1 trabajador a jornada completa; facturación ≤1 M€; escritura pública; mantener 3 años", art: "612-9" },
      { n: "Obligación de declarar por tener más de un pagador", imp: "Diferencia positiva entre cuota íntegra autonómica y estatal", lim: "—", renta: "No se establece", req: "No aplicable si pudo acogerse al procedimiento especial de retenciones", art: "612-10" },
      { n: "Alquiler de vivienda habitual de víctimas de violencia machista", imp: "20 % (25 % si discapacidad ≥65 % o hijo menor a cargo)", lim: "1.000 € (1.200 € en el 25 %)", renta: "Base imponible total menos mínimo personal y familiar ≤ 30.000 €", req: "Acreditar la condición (Ley 5/2008); máx. 3 ejercicios consecutivos", art: "612-11" },
      { n: "Inversión en cooperativas agrarias y de vivienda", imp: "20 % de las aportaciones desembolsadas", lim: "3.000 €/ejercicio (con traslado por insuficiencia de cuota)", renta: "No se establece", req: "Socio no temporal con ≤25 % de votos; cooperativa inscrita; mantener 5 años", art: "612-12" },
      { n: "Tramo autonómico por inversión en vivienda habitual (régimen transitorio)", imp: "7,5 % general; 15 % obras por discapacidad; 9 % adquisiciones anteriores al 30-07-2011", lim: "—", renta: "Para el 9 %: BI menos mínimo personal y familiar ≤ 30.000 €", req: "Para el 9 %: ≤32 años, o paro ≥183 días, o discapacidad ≥65 %, o un hijo", art: "613-1" }
    ]
  },

  asturias: {
    norma: "Decreto Legislativo 2/2014 (TR tributos cedidos)",
    id: "BOE-A-2015-945",
    url: "https://www.boe.es/buscar/act.php?id=BOE-A-2015-945",
    act: "31/12/2025",
    nota: "Los concejos en riesgo de despoblamiento se fijan por Decreto 83/2025.",
    items: [
      { n: "Acogimiento no remunerado de mayores de 65 años", imp: "500 € por persona", lim: "—", renta: "BI ≤ 26.000 / 37.000 €", req: "Convivencia >183 días; sin ayudas del Principado; sin parentesco ≤3.er grado", art: "3" },
      { n: "Adquisición o adecuación de vivienda habitual para contribuyentes con discapacidad", imp: "3 % de lo satisfecho", lim: "Base máx. 15.000 €", renta: "No se establece", req: "Discapacidad ≥65 % (propia o de conviviente con rentas ≤35.000 €); obras de accesibilidad", art: "4" },
      { n: "Inversión en vivienda habitual protegida", imp: "Hasta 5.000 € el ejercicio de adquisición/rehabilitación y hasta 1.000 € los siguientes", lim: "Esos importes", renta: "No se establece", req: "Vivienda protegida; remanente aplicable 3 ejercicios", art: "6" },
      { n: "Arrendamiento de vivienda habitual", imp: "10 %; 30 % en concejos en riesgo o si joven ≤35 años, familia numerosa, monoparental o víctima de violencia de género", lim: "500 € (1.500 € en los casos del 30 %)", renta: "BI ≤ 35.000 / 45.000 €", req: "Prorrateo entre cotitulares", art: "7" },
      { n: "Adopción internacional de menores", imp: "1.500 € por hijo", lim: "—", renta: "No se establece", req: "Convivencia con el declarante", art: "9" },
      { n: "Partos múltiples (o 2+ adopciones en la misma fecha)", imp: "1.000 € por hijo", lim: "—", renta: "No se establece", req: "Convivencia; prorrateo", art: "10" },
      { n: "Familias numerosas", imp: "1.000 € (general) / 2.000 € (especial)", lim: "—", renta: "Solo en las equiparadas: BI ≤ 35.000 / 45.000 €", req: "Título vigente a fecha de devengo; convivencia", art: "11" },
      { n: "Familias monoparentales", imp: "500 €", lim: "—", renta: "BI ≤ 45.000 €", req: "Descendientes a cargo con rentas ≤8.000 €; no convivir con otra persona; no en custodia compartida", art: "12" },
      { n: "Acogimiento familiar de menores", imp: "500 € por menor (250 € si convivencia >90 y <183 días)", lim: "—", renta: "No se establece", req: "Excluido el preadoptivo; ≥183 días", art: "13" },
      { n: "Certificación de la gestión forestal sostenible", imp: "30 % de lo invertido", lim: "1.000 €", renta: "No se establece", req: "Propietarios de montes en Asturias con certificación", art: "14" },
      { n: "Gastos de descendientes en centros de 0 a 3 años", imp: "15 % (30 % en concejos en riesgo)", lim: "500 €/descendiente (1.000 € en concejos en riesgo)", renta: "BI ≤ 26.000 / 37.000 € (35.000 / 45.000 € en concejos en riesgo)", req: "Convivencia; se minora por ayudas; incompatible con art. 14 duodecies", art: "14 bis" },
      { n: "Adquisición de libros de texto y material escolar", imp: "Conjunta 100 / 75 / 50 € por descendiente según tramos; individual 50 / 37,50 / 25 €", lim: "Familia numerosa: 150 € conjunta / 75 € individual", renta: "BI ≤ 26.000 / 37.000 €", req: "Primaria y ESO; se minora por becas", art: "14 ter" },
      { n: "Nacimiento o adopción de 2.º y sucesivos hijos en concejos en riesgo", imp: "300 € por hijo", lim: "—", renta: "BI ≤ 35.000 / 45.000 €", req: "Residencia en concejo en riesgo; convivencia", art: "14 quáter" },
      { n: "Establecimiento como autónomo en concejos en riesgo", imp: "1.000 €", lim: "—", renta: "BI ≤ 35.000 / 45.000 €", req: "Alta mantenida ≥1 año; no haber cesado en la misma actividad en 6 meses", art: "14 quinquies" },
      { n: "Gastos de transporte público (concejos en riesgo)", imp: "Importe de abonos nominales; +10 % por descendiente que estudie fuera", lim: "100 € (300 € el tramo adicional)", renta: "BI ≤ 35.000 / 45.000 €", req: "Abonos nominales; factura", art: "14 sexies" },
      { n: "Gastos de formación en trabajos cualificados de I+D, científicos o técnicos", imp: "Importe de los gastos", lim: "2.000 €", renta: "No se establece", req: "≤3 años desde el fin de la formación; residencia ≥3 años; una sola vez", art: "14 septies" },
      { n: "Traslado del domicilio fiscal a Asturias por motivos laborales", imp: "15 % de los gastos del traslado", lim: "1.000 € (2.000 € si trabajos cualificados de I+D)", renta: "No se establece", req: "No residente en Asturias los 4 años previos; permanencia ≥3 años", art: "14 octies" },
      { n: "Adquisición o rehabilitación de vivienda habitual para determinados colectivos", imp: "5 % en concejos en riesgo (10 % si ≤35 años, familia numerosa o monoparental); 5 % para ≤35 años si el valor ≤250.000 €", lim: "Base máx. 10.000 €", renta: "BI ≤ 35.000 / 45.000 €", req: "Mantener el domicilio ≥3 años", art: "14 decies" },
      { n: "Adquisición de vehículos eléctricos", imp: "15 %", lim: "Base máx. 50.000 € (minorada por ayudas)", renta: "No se establece", req: "Nuevos o km 0 enchufables (MOVES III), 2022-2026; no afectos a actividad", art: "14 undecies" },
      { n: "Cuidado de descendientes de hasta 25 años", imp: "600 € por descendiente", lim: "—", renta: "BI ≤ 35.000 / 45.000 €", req: "Convivencia; se extiende hasta los 26; incompatible con art. 14 bis", art: "14 duodecies" },
      { n: "Emancipación de jóvenes de hasta 35 años", imp: "Hasta 1.000 €", lim: "1.000 €", renta: "BI ≤ 35.000 / 45.000 €", req: "Dejar de convivir con ascendientes y trasladarse a vivienda en Asturias; se pierde si retorna antes de 3 años", art: "14 terdecies" },
      { n: "Ayudas o subvenciones a enfermos de ELA", imp: "Tipos medios de gravamen sobre el importe integrado", lim: "—", renta: "No se establece", req: "Subvención del Principado integrada en la base", art: "14 quaterdecies" },
      { n: "Gastos del arrendador de viviendas", imp: "Importe de los gastos (conservación, contratos, seguros, certificados)", lim: "500 €/año", renta: "No se establece", req: "Arrendamiento con sostenibilidad social del precio", art: "14 quindecies" },
      { n: "Gastos vitales de contribuyentes de hasta 35 años (incluye deporte)", imp: "Importe de los gastos: vivienda y suministros, educativos, transporte, tecnología, deporte y cultura", lim: "2.000 € (≤25 años); 1.500 € (26-30); 1.000 € (30-35)", renta: "BI ≤ 28.000 €", req: "Justificación por factura", art: "14 sexdecies" },
      { n: "Descendientes en caso de fallecimiento de un progenitor por accidente laboral", imp: "1.000 € por descendiente", lim: "—", renta: "No se establece", req: "Mientras genere mínimo por descendientes", art: "14 septendecies" },
      { n: "Inversión en entidades nuevas o de reciente creación", imp: "30 %", lim: "6.000 €/año", renta: "No se establece", req: "≤40 % del capital; mantener 3 años; domicilio en Asturias, microempresa/pyme, actividad y empleo", art: "14 octodecies" },
      { n: "Gastos derivados de la enfermedad celíaca", imp: "100 € por miembro diagnosticado", lim: "—", renta: "BI ≤ 35.000 / 45.000 €", req: "Informe médico oficial con diagnóstico definitivo", art: "14 novodecies" }
    ]
  },

  andalucia: {
    norma: "Ley 5/2021, de Tributos Cedidos",
    id: "BOE-A-2021-17915",
    url: "https://www.boe.es/buscar/act.php?id=BOE-A-2021-17915",
    act: "31/12/2025",
    nota: "«BI» = suma de bases imponibles general y del ahorro (individual / conjunta).",
    items: [
      { n: "Inversión en vivienda habitual protegida y por jóvenes", imp: "6 % de lo satisfecho", lim: "Base máx. 9.040 €/año", renta: "BI ≤ 25.000 / 30.000 €", req: "Vivienda protegida en Andalucía o adquirente menor de 35 años", art: "9" },
      { n: "Alquiler de vivienda habitual", imp: "15 %", lim: "1.200 €/año (1.500 € con discapacidad)", renta: "BI ≤ 25.000 / 30.000 €", req: "Menor de 35 o mayor de 65 años, o víctima de violencia doméstica/terrorismo; NIF del arrendador", art: "10" },
      { n: "Nacimiento, adopción o acogimiento familiar de menores", imp: "200 € por hijo/menor (400 € en municipios con problemas de despoblación); +200 € por hijo en partos múltiples", lim: "—", renta: "No se establece", req: "Reparto al 50 %; incompatible con arts. 12 y 14; en acogimiento, ≥90 días y sin ayudas", art: "11" },
      { n: "Adopción de hijos en el ámbito internacional", imp: "600 € por hijo", lim: "—", renta: "BI ≤ 80.000 / 100.000 €", req: "Adopción inscrita en el Registro Civil en el periodo", art: "12" },
      { n: "Familia monoparental (y ascendientes mayores de 75 años)", imp: "100 € + 100 € por cada ascendiente conviviente", lim: "—", renta: "BI ≤ 80.000 / 100.000 €", req: "Monoparental a fecha de devengo; ascendiente que genere el mínimo >75 años", art: "13" },
      { n: "Familia numerosa", imp: "200 € (general) / 400 € (especial)", lim: "—", renta: "BI ≤ 25.000 / 30.000 €", req: "Ser ascendiente de familia numerosa; también hermanos huérfanos", art: "14" },
      { n: "Gastos educativos", imp: "15 % de enseñanza escolar o extraescolar de idiomas e informática", lim: "150 €/año por descendiente", renta: "BI ≤ 80.000 / 100.000 €", req: "Descendientes que generen el mínimo", art: "15" },
      { n: "Contribuyentes con discapacidad", imp: "150 €", lim: "—", renta: "BI ≤ 25.000 / 30.000 €", req: "Tener la consideración de persona con discapacidad", art: "16" },
      { n: "Cónyuges o parejas de hecho con discapacidad", imp: "100 €", lim: "—", renta: "BI ≤ 25.000 / 30.000 €", req: "Discapacidad ≥65 % del cónyuge que no declare individualmente; incompatible con art. 16", art: "17" },
      { n: "Asistencia a personas con discapacidad", imp: "100 € por persona; además 20 % de la cuota de empleados de hogar", lim: "500 €/año (en el tramo del 20 %)", renta: "BI ≤ 80.000 / 100.000 €", req: "Derecho al mínimo por discapacidad de ascendientes/descendientes", art: "18" },
      { n: "Ayuda doméstica", imp: "20 % de lo satisfecho a la Seguridad Social", lim: "500 €/año", renta: "No se establece", req: "Titular del hogar afiliado en Andalucía; hijos con derecho al mínimo y ambos cónyuges con rentas, o ≥75 años", art: "19" },
      { n: "Inversión en acciones y participaciones (constitución o ampliación)", imp: "20 % (50 % si participadas por universidades o centros de investigación)", lim: "4.000 €/año (12.000 € en el 50 %)", renta: "No se establece", req: "Participación familiar ≤40 %; mantener 3 años; domicilio en Andalucía, actividad y empleo", art: "20" },
      { n: "Gastos de defensa jurídica de la relación laboral", imp: "Importe satisfecho", lim: "200 €", renta: "No se establece", req: "Despido, extinción de contrato y reclamación de cantidades", art: "21" },
      { n: "Donativos con finalidad ecológica", imp: "10 %", lim: "150 €", renta: "No se establece", req: "Entes públicos andaluces o entidades sin fin lucrativo de defensa del medio ambiente", art: "22" },
      { n: "Fomento del ejercicio físico y la práctica deportiva", imp: "15 % de cuotas de gimnasios, centros, clubes y federaciones", lim: "100 €/año", renta: "No se establece", req: "Del contribuyente, cónyuge o quienes den derecho a mínimos. Novedad en vigor 01/01/2026 con efectos desde 01/01/2025", art: "22 bis" },
      { n: "Gastos veterinarios de animales de compañía y perros de asistencia", imp: "30 % de los gastos veterinarios", lim: "100 €/año", renta: "BI ≤ 80.000 / 100.000 €", req: "1 año tras la adquisición (3 si adopción); factura veterinaria; desde 1-1-2025", art: "22 ter" },
      { n: "Familias con enfermedad celíaca diagnosticada", imp: "100 € por integrante con celiaquía", lim: "—", renta: "No se establece", req: "Informe médico oficial; prorrateo por partes iguales", art: "22 quater" }
    ]
  },

  cvalenciana: {
    norma: "Ley 13/1997 (tramo autonómico del IRPF y tributos cedidos)",
    id: "BOE-A-1998-8202",
    url: "https://www.boe.es/buscar/act.php?id=BOE-A-1998-8202",
    act: "30/03/2026",
    nota: "Límite general de renta (art. 4.Cuatro): base liquidable ≤ 30.000 € individual / 47.000 € conjunta (35.000 / 58.000 € para familia numerosa o monoparental especial). Los importes solo se aplican íntegros por debajo de 27.000 / 44.000 €, con reducción proporcional hasta el límite.",
    items: [
      { n: "Nacimiento o adopción", imp: "600 € (1.º) / 750 € (2.º) / 900 € (3.º y sucesivos)", lim: "—", renta: "Límite general", req: "También los dos ejercicios posteriores; prorrateo", art: "4.Uno a).1" },
      { n: "Acogimiento familiar o guarda con fines de adopción", imp: "600 / 750 / 900 €", lim: "—", renta: "Límite general", req: "Debe abarcar todo el periodo (si no, prorrateo); >183 días para 2.º y 3.º", art: "a).2" },
      { n: "Nacimiento o adopción múltiples", imp: "246 €", lim: "—", renta: "Límite general", req: "Parto múltiple o dos adopciones en la misma fecha", art: "b)" },
      { n: "Nacimiento o adopción de persona con discapacidad", imp: "246 € (único hijo) / 303 €", lim: "—", renta: "Límite general", req: "Discapacidad ≥65 %, o intelectual/mental ≥33 %", art: "c)" },
      { n: "Familia numerosa o monoparental", imp: "330 € (general) / 660 € (especial)", lim: "—", renta: "General 30.000/47.000; especial 35.000/58.000 €", req: "La aplica el contribuyente con quien conviven los demás miembros", art: "d)" },
      { n: "Custodia en guarderías y centros de primer ciclo de infantil (<3 años)", imp: "15 %", lim: "297 € por menor", renta: "Límite general", req: "Ambos progenitores con rendimientos del trabajo o de actividades", art: "e)" },
      { n: "Conciliación del trabajo con la vida familiar", imp: "460 € por hijo mayor de 3 y menor de 5 años", lim: "Tope: cotizaciones devengadas", renta: "Límite general", req: "Solo la madre (padre si fallece o custodia exclusiva); alta en SS", art: "f)" },
      { n: "Contribuyentes con discapacidad ≥33 % y edad ≥65 años", imp: "197 €", lim: "—", renta: "Límite general", req: "No procede si percibe prestación exenta por esa discapacidad", art: "g)" },
      { n: "Ascendientes mayores de 75 años (o >65 con discapacidad)", imp: "197 € por ascendiente", lim: "—", renta: "Límite general", req: "Convivencia ≥ mitad del periodo; ascendiente sin rentas >8.000 €", art: "h)" },
      { n: "Contratación indefinida de empleados de hogar para cuidado", imp: "50 % de las cuotas de cotización", lim: "660 € (un menor) / 1.100 € (dos o más o monoparental); 330 / 550 € por ascendientes", renta: "Límite general", req: "Menores de 5 años o ascendientes >75; incompatible con e), f) y h)", art: "i)" },
      { n: "Arrendamiento por debajo del precio de referencia (arrendador)", imp: "5 % de los rendimientos íntegros", lim: "Base máx. 3.300 €/año", renta: "No se establece", req: "Contrato iniciado en el periodo; renta ≤ precio de referencia; fianza depositada", art: "j)" },
      { n: "Primera adquisición de vivienda habitual por ≤35 años", imp: "5 % de lo satisfecho (sin intereses)", lim: "—", renta: "Límite general", req: "Primera adquisición; edad ≤35 a fecha de devengo", art: "k)" },
      { n: "Adquisición de vivienda habitual por personas con discapacidad", imp: "5 % de lo satisfecho (sin intereses)", lim: "—", renta: "Límite general", req: "Discapacidad ≥65 % o intelectual/mental ≥33 %", art: "l)" },
      { n: "Ayudas públicas para adquisición o rehabilitación de vivienda", imp: "112 € o el tipo medio autonómico sobre la ayuda", lim: "—", renta: "No se establece", req: "Ayuda de la Generalitat o del Estado; incompatible con k) y l)", art: "m)" },
      { n: "Arrendamiento de la vivienda habitual", imp: "20 % / 25 % (una condición) / 30 % (dos o más)", lim: "800 / 950 / 1.100 €", renta: "Límite general", req: "Condiciones: ≤35 años, discapacidad ≥65 %, víctima de violencia de género. Contrato ≥1 año; sin otra vivienda a <50 km", art: "n)" },
      { n: "Arrendamiento por actividad en municipio distinto", imp: "10 %", lim: "224 €", renta: "Límite general", req: "Vivienda en la C. Valenciana a >50 km de la anterior; no retribuido por el empleador", art: "ñ)" },
      { n: "Autoconsumo eléctrico y energías renovables en la vivienda", imp: "40 % (20 % en segundas residencias)", lim: "Base máx. 8.800 € por vivienda y ejercicio", renta: "No se establece", req: "No instalaciones obligatorias por el CTE; pago trazable; exceso trasladable 4 años", art: "o)" },
      { n: "Donaciones con finalidad ecológica", imp: "20 % primeros 250 € + 25 % del resto", lim: "—", renta: "No se establece", req: "Generalitat, entes locales o entidades sin fin lucrativo medioambiental", art: "p)" },
      { n: "Donaciones relativas al patrimonio cultural valenciano", imp: "20 % primeros 250 € + 25 % del resto", lim: "—", renta: "No se establece", req: "Bienes del Inventario General o donaciones para su conservación", art: "q)" },
      { n: "Donaciones para el fomento del valenciano", imp: "20 % primeros 250 € + 25 % del resto", lim: "—", renta: "No se establece", req: "Generalitat, entes locales, universidades o entidades del censo", art: "r)" },
      { n: "Donaciones y cesiones de uso para fines culturales, científicos o deportivos no profesionales", imp: "25 % (los primeros 250 € al 20 % si aplica la estatal)", lim: "—", renta: "No se establece", req: "Proyectos declarados de interés social (Ley 20/2018 de mecenazgo)", art: "s)" },
      { n: "Contribuyentes con dos o más descendientes", imp: "10 % de la cuota íntegra autonómica", lim: "—", renta: "Suma de bases imponibles ≤ 30.000 €", req: "Descendientes que generen el mínimo", art: "t)" },
      { n: "Incremento del coste de la financiación de la vivienda habitual", imp: "50 % de la diferencia positiva de intereses", lim: "100 €", renta: "Límite general", req: "Préstamo para vivienda habitual; sin deducción estatal por inversión", art: "u)" },
      { n: "Adquisición de material escolar", imp: "110 € por hijo escolarizado", lim: "—", renta: "Límite general", req: "Primaria, ESO o educación especial; contribuyente en desempleo e inscrito como demandante", art: "v)" },
      { n: "Obras de conservación, sostenibilidad y accesibilidad en la vivienda habitual", imp: "20 % (hasta 50 % en accesibilidad por discapacidad ≥33 %)", lim: "Base máx. 5.500 €/año", renta: "Límite general", req: "Excluye garajes, jardines y piscinas; NIF del ejecutor y pago trazable", art: "w)" },
      { n: "Abonos culturales", imp: "21 %", lim: "Base máx. 165 €", renta: "Base liquidable < 50.000 €", req: "Empresas adheridas al convenio (Abono Cultural Valenciano)", art: "x)" },
      { n: "Adquisición de bicicletas urbanas y vehículos eléctricos de movilidad personal", imp: "10 %", lim: "Importe máximo subvencionable +10 %", renta: "Límite general", req: "Un único vehículo por contribuyente y periodo", art: "y)" },
      { n: "Suscripción de acciones o participaciones (sociedades y cooperativas)", imp: "30 % (+15 % adicional si PYME innovadora)", lim: "6.600 € (15.000 € con el incremento)", renta: "No se establece", req: "Domicilio en la C. Valenciana 3 años; requisitos temporales de constitución/ampliación", art: "z)" },
      { n: "Residencia habitual en municipio en riesgo de despoblamiento", imp: "330 €, +132 / +198 / +264 € por uno, dos, o tres o más descendientes", lim: "—", renta: "No se establece", req: "Los importes adicionales son incompatibles con a), b) y c) por el mismo descendiente", art: "aa)" },
      { n: "Tratamientos de fertilidad (mujeres de 40 a 45 años)", imp: "100 €", lim: "—", renta: "Límite general", req: "Clínicas o centros autorizados", art: "ab)" },
      { n: "Gastos de salud (enfermedades raras, daño cerebral, bucodental, salud mental, lentes)", imp: "Hasta 100 € (150 € familia numerosa/monoparental); 30 % en bucodental, salud mental y lentes", lim: "150 € (bucodental y salud mental); 100 € (lentes)", renta: "Base liquidable ≤ 60.000 / 78.000 €", req: "Compatibles entre sí; cubre cónyuge y quienes den derecho a mínimos; excluye seguros", art: "ac)" },
      { n: "Gastos asociados a la práctica del deporte y actividades saludables", imp: "30 % (50 % si >65 años o discapacidad ≥33 %; 100 % si >75 años o discapacidad ≥65 %)", lim: "150 €", renta: "Base liquidable ≤ 60.000 / 78.000 € (íntegro por debajo de 54.000 / 72.000)", req: "Cubre cónyuge y quienes den derecho a mínimos familiares", art: "ad)" },
      { n: "Fomento y formación musicales", imp: "Cantidades satisfechas (sin porcentaje en la norma)", lim: "150 €", renta: "Base liquidable ≤ 60.000 / 78.000 €", req: "Conservatorios y escuelas inscritas, sociedades musicales FSMCV, instrumentos, partituras y entradas", art: "ae)" }
    ]
  },

  galicia: {
    norma: "Decreto Legislativo 1/2011 (TR tributos cedidos)",
    id: "BOE-A-2011-18161",
    url: "https://www.boe.es/buscar/act.php?id=BOE-A-2011-18161",
    act: "27/03/2026",
    nota: "Todas están en el art. 5. «BI–mín.» = base imponible total menos los mínimos personal y familiar.",
    items: [
      { n: "Nacimiento o adopción de hijos", imp: "300 € (BI–mín. >22.000 €); 360 € (≤22.000 €), 1.200 € el 2.º y 2.400 € el 3.º y siguientes; +20 % en municipios <5.000 hab.; se duplica si el hijo tiene discapacidad ≥33 %", lim: "—", renta: "Tramos ≤22.000 / >22.000 €; en los dos ejercicios siguientes 22.000-31.000 €", req: "Convivencia; se extiende a los dos periodos siguientes; prorrateo al 50 %", art: "5.Dos" },
      { n: "Familias con hijos e hijas", imp: "250 € con dos descendientes; con título de familia numerosa 250 € (hasta dos hijos), 400 € (especial), +250 € por hijo adicional; se duplica con discapacidad ≥65 %", lim: "—", renta: "No se establece", req: "Las dos modalidades son incompatibles entre sí; prorrateo", art: "5.Tres" },
      { n: "Acogimiento", imp: "300 € por menor acogido", lim: "—", renta: "No se establece", req: "Formalizado por el órgano de menores de la Xunta; no si se adopta en el periodo", art: "5.Cuatro" },
      { n: "Cuidado de hijos menores", imp: "30 %", lim: "400 € (600 € con dos o más hijos)", renta: "BI–mín. ≤ 22.000 / 31.000 €", req: "Hijos de 3 o menos años; ambos progenitores en activo; empleada de hogar o escuela infantil", art: "5.Cinco" },
      { n: "Contribuyentes con discapacidad ≥65 % y edad ≥65 años que precisen ayuda de terceros", imp: "10 % de lo satisfecho", lim: "600 €", renta: "BI–mín. ≤ 22.000 / 31.000 €", req: "Acreditar la necesidad de ayuda; no ser usuario de residencias públicas o concertadas", art: "5.Seis" },
      { n: "Alquiler de vivienda habitual", imp: "10 % (20 % con dos o más hijos menores); se duplica con discapacidad ≥33 %", lim: "300 € por contrato (600 € en el 20 %)", renta: "Base imponible antes de mínimos ≤ 22.000 €", req: "Edad ≤35 años; contrato posterior a 1-1-2003; fianza en el IGVS", art: "5.Siete" },
      { n: "Uso de nuevas tecnologías en los hogares", imp: "30 % de cuota de alta y cuotas mensuales", lim: "100 €", renta: "No se establece", req: "Solo el ejercicio de la suscripción; uso exclusivo del hogar; no por cambio de compañía", art: "5.Ocho" },
      { n: "Inversión en entidades nuevas o de reciente creación", imp: "30 % (+15 % si PYME innovadora, IEBT o participada por universidades)", lim: "6.000 € (9.000 € con el incremento)", renta: "No se establece", req: "Participación entre 1 % y 40 %; domicilio en Galicia 3 años; ≥1 empleado residente; mantener 3 años", art: "5.Nueve" },
      { n: "Inversión y financiación de entidades nuevas o de reciente creación", imp: "30 % de la inversión y 30 % de préstamos o garantías (+15 % adicional)", lim: "Límite conjunto 20.000 € (35.000 € con el incremento)", renta: "No se establece", req: "Sin funciones ejecutivas 10 años; préstamos >5 años; incompatible con Nueve y Once", art: "5.Diez" },
      { n: "Inversión en el segmento de empresas en expansión del MAB", imp: "15 %", lim: "4.000 €", renta: "No se establece", req: "≤10 % del capital; mantener 3 años; domicilio en Galicia; prorrateo en 4 ejercicios", art: "5.Once" },
      { n: "Donaciones para investigación, desarrollo científico e innovación tecnológica", imp: "25 %", lim: "10 % de la cuota íntegra autonómica", renta: "No se establece", req: "Centros de investigación de universidades gallegas o promovidos por la Xunta", art: "5.Doce" },
      { n: "Instalaciones de climatización y/o ACS con energías renovables (autoconsumo)", imp: "5 %", lim: "280 €", renta: "No se establece", req: "Registro de la instalación en la Oficina Virtual de Industria; pago no en efectivo", art: "5.Trece" },
      { n: "Rehabilitación de inmuebles en centros históricos", imp: "15 %", lim: "9.000 €", renta: "No se establece", req: "Centros históricos determinados por orden; coste >25 % del precio de adquisición", art: "5.Catorce" },
      { n: "Inversión en empresas de actividades agrarias", imp: "20 % de las cantidades o del valor aportado", lim: "Límite conjunto 20.000 €", renta: "No se establece", req: "Sociedades de fomento forestal, cooperativas agrarias o de recuperación de tierra; mantener 5 años", art: "5.Quince" },
      { n: "Subvenciones por los incendios forestales de 2025 (Peifoga situación 2)", imp: "Tipos medios de gravamen sobre el importe de la subvención", lim: "—", renta: "No se establece", req: "Ayudas del Decreto 76/2025 integradas en la base general", art: "5.Dieciséis" },
      { n: "Obras de mejora de eficiencia energética en viviendas", imp: "15 % de lo invertido, más honorarios del certificado y tasas", lim: "Base máx. 9.000 €; 150 € por el certificado", renta: "No se establece", req: "Subir al menos una letra de calificación energética; inscripción en el Registro; incompatible con Trece", art: "5.Dieciocho" },
      { n: "Ayudas y subvenciones a deportistas de alto nivel de Galicia", imp: "Tipos medios de gravamen sobre la subvención", lim: "—", renta: "No se establece", req: "Condición reconocida por la Xunta; sin rendimientos de actividad económica", art: "5.Diecinueve" },
      { n: "Adquisición y rehabilitación de viviendas en aldeas modelo", imp: "15 % de lo satisfecho", lim: "Base máx. 9.000 €/año (habitual) o 4.500 €/año", renta: "No se establece", req: "Terrenos integrados en proyectos de aldeas modelo; incompatible con Trece y Dieciocho", art: "5.Veinte" },
      { n: "Inversión en entidades de proyectos de especial interés público, social o económico", imp: "20 %", lim: "Base máx. 10.000 € por entidad", renta: "No se establece", req: "Objeto social exclusivo (arts. 17 y 20 de la Ley 2/2024); incompatible con otras del artículo", art: "5.Veintiuno" },
      { n: "Adecuación de un inmueble vacío para arrendarlo como vivienda", imp: "15 % de reparación, conservación y gastos necesarios", lim: "Base máx. 9.000 € por vivienda; 3.000 €/año (6.000 € con varias)", renta: "No se establece", req: "Inmueble vacío ≥1 año; obras en 2 años; arrendado en ≤6 meses; valor ≤250.000 €; máx. 3 viviendas", art: "5.Veintidós" },
      { n: "Arrendamiento de viviendas vacías", imp: "500 € por vivienda", lim: "—", renta: "No se establece", req: "Vacía ≥1 año; alquiler ≤700 €/mes; arrendatario no pariente ≤3.er grado; máx. 3 viviendas", art: "5.Veintitrés" },
      { n: "Ayudas a personas con ELA o sus fenotipos", imp: "Tipos medios de gravamen sobre la ayuda", lim: "—", renta: "No se establece", req: "Ayuda pública integrada en la base general", art: "5.Veinticuatro" },
      { n: "Adquisición de libros de texto y material escolar", imp: "15 %", lim: "105 € por descendiente matriculado", renta: "Renta per cápita de la unidad familiar ≤ 30.000 €", req: "Primaria, ESO y educación especial en centros sostenidos con fondos públicos; incompatible con becas", art: "5.Veinticinco" },
      { n: "Ayudas a personas afectadas por la talidomida (1950-1985)", imp: "Tipos medios de gravamen sobre la ayuda", lim: "—", renta: "No se establece", req: "Ayuda pública integrada en la base general", art: "5.Veintiséis" }
    ]
  },

  canarias: {
    norma: "Decreto-Legislativo 1/2009 (TR tributos cedidos)",
    id: "BOC-j-2009-90008",
    url: "https://www.boe.es/buscar/act.php?id=BOC-j-2009-90008",
    act: "29/12/2025",
    nota: "«Renta» = base imponible general + del ahorro (art. 17). La suma de deducciones no puede superar la cuota íntegra autonómica (art. 18).",
    items: [
      { n: "Donaciones con finalidad ecológica", imp: "10 %", lim: "10 % de la cuota íntegra autonómica y 150 €", renta: "No se fija", req: "Entes públicos canarios o entidades sin fin lucrativo de defensa del medio ambiente", art: "3" },
      { n: "Donaciones para rehabilitación o conservación del patrimonio histórico de Canarias", imp: "20 %", lim: "10 % de la cuota íntegra autonómica y 150 €", renta: "No se fija", req: "Bienes en Canarias inscritos en el Registro Canario de BIC", art: "4" },
      { n: "Donaciones para fines culturales, deportivos, investigación o docencia", imp: "15 %", lim: "5 % de la cuota íntegra autonómica; base máx. 50.000 € o 3.000 €/año según el destinatario", renta: "No se fija", req: "Destinatarios tasados (Administración canaria, universidades, empresas de base tecnológica…)", art: "4 bis" },
      { n: "Donaciones a entidades sin ánimo de lucro", imp: "20 % hasta 150 € de base y 15 % el resto (17,5 % si donación recurrente)", lim: "Base ≤10 % de la base liquidable", renta: "No se fija", req: "Entidades de la Ley 49/2002; incompatible con arts. 3 y 4 bis", art: "4 ter" },
      { n: "Restauración, rehabilitación o reparación de bienes del patrimonio", imp: "10 %", lim: "10 % de la cuota íntegra autonómica (y límite conjunto del 15 %, art. 14 quater)", renta: "No se fija", req: "Inmuebles en Canarias inscritos en el Registro Canario de BIC; obras autorizadas", art: "6" },
      { n: "Gastos de estudios de educación superior", imp: "1.800 € por descendiente que estudia fuera de la isla (1.920 € si base liquidable <37.062 €); 900 € si estudia en la misma isla trasladando domicilio", lim: "40 % de la cuota íntegra autonómica", renta: "Rentas ≤ 46.455 / 61.770 €", req: "Descendiente soltero <25 años con rentas ≤8.000 €; curso completo o 30 créditos; sin oferta pública en la isla", art: "7" },
      { n: "Gastos de estudios no superiores", imp: "Hasta 133 € por el primer descendiente y 66 € por cada uno de los restantes", lim: "133 € + 66 €/hijo adicional", renta: "Rentas ≤ 46.455 / 61.770 €", req: "Libros, material, transporte, uniforme y comedor; factura", art: "7 bis" },
      { n: "Traslado de residencia (entre islas, por trabajo)", imp: "300 € (el ejercicio del traslado y el siguiente)", lim: "Parte autonómica de la cuota de trabajo y actividades", renta: "Rentas ≤ 46.455 / 61.770 €", req: "Traslado por trabajo y permanencia el año del traslado y los 3 siguientes", art: "8" },
      { n: "Inversión en entidades nuevas o de reciente creación", imp: "20 % (30 % si participadas por universidades/centros de investigación, sociedades laborales y cooperativas)", lim: "4.000 €/año (6.000 € en el 30 %)", renta: "No se fija", req: "Participación familiar <40 %; mantener 3 años; domicilio en Canarias, actividad y 1 empleado", art: "9" },
      { n: "Nacimiento o adopción de hijos", imp: "265 € (1.º y 2.º), 530 € (3.º), 796 € (4.º), 928 € (5.º y sucesivos); +600 € o 1.100 € si discapacidad ≥65 %", lim: "—", renta: "Rentas ≤ 46.455 / 61.770 €", req: "Convivencia; prorrateo entre progenitores", art: "10" },
      { n: "Contribuyentes con discapacidad y mayores de 65 años", imp: "400 € (discapacidad ≥33 %) y 160 € (>65 años), compatibles entre sí", lim: "—", renta: "Rentas ≤ 46.455 / 61.770 €", req: "Circunstancias a fecha de devengo", art: "11" },
      { n: "Acogimiento de menores", imp: "330 € por menor", lim: "—", renta: "No se fija", req: "Acogimiento de urgencia, temporal o permanente con convivencia todo el periodo (si no, prorrateo)", art: "11 bis" },
      { n: "Familias monoparentales", imp: "133 €", lim: "—", renta: "Rentas ≤ 46.455 / 61.770 €", req: "No convivir con otra persona distinta de los descendientes; descendientes con rentas ≤8.000 €", art: "11 ter" },
      { n: "Gastos de custodia en guarderías", imp: "18 %", lim: "530 €/año por descendiente", renta: "Rentas ≤ 46.455 / 61.770 €", req: "Descendientes <3 años; guardería autorizada; factura y NIF", art: "12" },
      { n: "Familia numerosa", imp: "597 € (general) / 796 € (especial); 1.326 € / 1.459 € si hay discapacidad ≥65 %", lim: "—", renta: "No se fija", req: "Título vigente a fecha de devengo; compatible con la de nacimiento", art: "13" },
      { n: "Inversión en vivienda habitual", imp: "5 % si renta <26.035 €; 3,5 % si ≥26.035 y <46.455 €; 5,5 % y 4 % si menor de 40 años", lim: "Base máx. 6.000 €/año (y límite conjunto del 15 %)", renta: "Implícito: renta < 46.455 €", req: "Requisitos del art. 68.1 LIRPF en su redacción a 1-1-2012", art: "14" },
      { n: "Obras de rehabilitación energética de la vivienda habitual", imp: "12 %", lim: "10 % de la cuota íntegra autonómica; base máx. 7.000 €", renta: "No se fija", req: "Mejora acreditada con certificados energéticos; pago no en efectivo; incompatible con arts. 6 y 14", art: "14 bis" },
      { n: "Obras de adecuación de la vivienda por discapacidad", imp: "14 % (18 % si mayor de 65 años)", lim: "Base máx. 15.000 €", renta: "Si la discapacidad es de un conviviente, este no puede tener rentas >35.735 €", req: "Discapacidad ≥65 %; obras acreditadas por la consejería", art: "14 ter" },
      { n: "Alquiler de vivienda habitual", imp: "24 %", lim: "740 €/año (760 € si menor de 40 o ≥75 años)", renta: "Rentas ≤ 46.455 € (+15.315 € en conjunta)", req: "El alquiler debe exceder del 10 % de las rentas; NIF del arrendador y referencia catastral", art: "15" },
      { n: "Arrendamiento vinculado a dación en pago", imp: "25 %", lim: "1.200 €/año", renta: "Renta ≤ 46.455 € (+15.315 € en conjunta)", req: "Vinculado a la dación en pago del art. 35 bis del propio texto refundido", art: "15 bis" },
      { n: "Adecuación de un inmueble para arrendarlo como vivienda habitual", imp: "10 %", lim: "150 € por inmueble", renta: "No se fija", req: "Reparación, formalización, seguros y certificados; factura; incompatible con art. 15 quater", art: "15 ter" },
      { n: "Primas de seguros de impago de rentas de arrendamiento", imp: "75 %", lim: "150 €/año", renta: "No se fija", req: "Contrato ≥1 año; fianza depositada; renta mensual ≤800 €", art: "15 quater" },
      { n: "Puesta de viviendas en el mercado de arrendamiento habitual", imp: "1.000 € por inmueble", lim: "Máximo 5 inmuebles", renta: "No se fija", req: "Con imputación de renta el año anterior; contrato ≥3 años; arrendatario no pariente ≤3.er grado", art: "16" },
      { n: "Contribuyentes desempleados", imp: "120 €", lim: "—", renta: "Rendimientos del trabajo >15.876 € y ≤22.000 €; resto de bases ≤1.600 €", req: "Desempleo legal >6 meses del periodo", art: "16 bis" },
      { n: "Gastos de enfermedad", imp: "12 % de honorarios médicos/sanitarios y 12 % de aparatos (incluidas gafas y lentillas)", lim: "500 € individual / 700 € conjunta (+100 € si >65 años o discapacidad ≥65 %); 150 € si se superan los límites de renta", renta: "Rentas ≤ 46.455 / 61.770 € (por encima, límite de 150 €)", req: "Factura y NIF del prestador; excluye estética y seguros", art: "16 ter" },
      { n: "Familiares dependientes con discapacidad", imp: "600 € por persona; y 20 % de las cuotas de empleados de hogar", lim: "500 €/año en el tramo del 20 %", renta: "Rentas ≤ 46.455 / 61.770 €", req: "Derecho al mínimo por discapacidad de ascendientes/descendientes ≥65 %", art: "16 quater" },
      { n: "Cuotas de la Seguridad Social por empleados de hogar", imp: "20 %", lim: "500 €/año", renta: "No se fija", req: "Con derecho al mínimo por descendientes y rendimientos de trabajo/actividad, o ≥75 años, o >65 con discapacidad", art: "16 quinquies" }
    ]
  },

  baleares: {
    norma: "Decreto Legislativo 1/2014 (TR tributos cedidos)",
    id: "BOE-A-2014-6925",
    url: "https://www.boe.es/buscar/act.php?id=BOE-A-2014-6925",
    act: "01/04/2026",
    nota: "El parámetro de renta es la «base imponible total» (individual / conjunta). En familias numerosas y monoparentales los límites se incrementan un 20 % (30 % en numerosas de categoría especial).",
    items: [
      { n: "Inversiones de mejora de la sostenibilidad de la vivienda habitual", imp: "50 %", lim: "Base máx. 10.000 €/periodo", renta: "BI ≤ 33.000 / 52.800 €", req: "Vivienda en Illes Balears; mejorar al menos un nivel la calificación energética", art: "3" },
      { n: "Arrendamiento de la vivienda habitual", imp: "15 % (20 % para <30 años, discapacidad ≥33 %, familias numerosas o monoparentales y autónomos)", lim: "530 €/año (650 € en el 20 %)", renta: "BI ≤ 33.000 / 52.800 €", req: "Menores de 36 o mayores de 65 sin actividad; contrato ≥1 año; sin otra vivienda a <70 km", art: "3 bis" },
      { n: "Subvenciones por zona gravemente afectada por emergencia de protección civil", imp: "Tipo medio de gravamen sobre la subvención", lim: "—", renta: "No se fija", req: "Ayudas de la CAIB integradas en la base general", art: "3 ter" },
      { n: "Incremento del coste de préstamos hipotecarios a tipo variable", imp: "Diferencia entre intereses de 2026 y 2025", lim: "400 €", renta: "BI ≤ 33.000 / 52.800 €", req: "Solo ejercicio 2026; vivienda habitual; certificado bancario", art: "3 quater" },
      { n: "Gastos de adquisición de libros de texto", imp: "100 %", lim: "220 € por hijo (350 € para determinados colectivos)", renta: "BI ≤ 33.000 / 52.800 €", req: "Hijos que den derecho al mínimo; factura", art: "4" },
      { n: "Aprendizaje extraescolar de idiomas extranjeros", imp: "15 %", lim: "110 € por hijo", renta: "BI ≤ 33.000 / 52.800 €", req: "Hijos que cursen los estudios del art. 4; factura", art: "4 bis" },
      { n: "Estudios de educación superior fuera de la isla de residencia", imp: "1.800 € por descendiente", lim: "50 % de la cuota íntegra autonómica", renta: "BI ≤ 33.000 / 52.800 €", req: "Curso completo o 30 créditos; descendiente con rentas ≤8.000 €", art: "4 ter" },
      { n: "Arrendador de inmuebles destinados a vivienda permanente", imp: "75 % de primas de seguro de impago; 50 % de otros gastos", lim: "440 €/año (primas) y 1.500 € (otros; 1.800 € si se arrienda al sector público)", renta: "BI ≤ 52.800 / 84.480 €", req: "Contrato ≥1 año; fianza en el IBAVI; para el 50 %, no arrendada los 2 ejercicios anteriores y renta ≤15 €/m²", art: "4 quater" },
      { n: "Arrendamiento por traslado temporal de residencia por motivos laborales", imp: "15 %", lim: "440 €/año", renta: "BI ≤ 33.000 / 52.800 €", req: "Traslado a otra isla en la misma relación laboral, ≤3 años; fianza en el IBAVI", art: "4 quinquies" },
      { n: "Gastos por vivienda ocupada ilegalmente o suspensión del lanzamiento", imp: "40 %", lim: "500 €", renta: "BI ≤ 33.000 / 52.800 €", req: "Gastos tasados: IBI, residuos, suministros, comunidad, conservación, procedimientos judiciales", art: "4 sexties" },
      { n: "Donaciones a entidades de investigación, desarrollo científico o innovación", imp: "25 %", lim: "15 % de la cuota íntegra autonómica", renta: "No se fija", req: "A la CAIB, la UIB o entidades sin fin lucrativo inscritas; certificado", art: "5" },
      { n: "Mecenazgo cultural, científico y de consumo cultural", imp: "15 % (25 % si el beneficiario es la CAIB con proyecto propio)", lim: "660 €/ejercicio (1.200 € en el 25 %)", renta: "BI ≤ 33.000 / 52.800 € (no aplica en el 25 %)", req: "Ley 3/2015; prorrateo si la cesión dura <1 año", art: "5 bis" },
      { n: "Mecenazgo deportivo", imp: "15 %", lim: "660 €/ejercicio", renta: "BI ≤ 33.000 / 52.800 €", req: "Ley 6/2015 de mecenazgo deportivo", art: "5 ter" },
      { n: "Donaciones para el fomento de la lengua catalana", imp: "15 %", lim: "10 % de la cuota íntegra autonómica", renta: "No se fija", req: "A la CAIB, UIB o entidades inscritas; incompatible con el art. 5 bis", art: "5 quater" },
      { n: "Donaciones a entidades del tercer sector", imp: "25 %", lim: "Base máx. 165 €", renta: "No se fija", req: "Entidades de la Ley 3/2018 inscritas; certificado", art: "5 quinquies" },
      { n: "Declarantes con discapacidad o con descendientes con discapacidad", imp: "88 € (física/sensorial 33-65 %); 165 € (física/sensorial ≥65 %); 165 € (psíquica ≥33 %)", lim: "—", renta: "BI ≤ 33.000 / 52.800 €", req: "Por cada contribuyente o miembro de la unidad familiar residente en IB", art: "6" },
      { n: "Gastos de descendientes menores de 6 años por conciliación", imp: "40 % (50 % para determinados colectivos)", lim: "660 € (900 € en el 50 %)", renta: "BI ≤ 33.000 / 52.800 €", req: "Guarderías, custodia, comedor y extraescolares o cuidador; rendimientos de trabajo o actividad; pago bancario", art: "6 bis" },
      { n: "Nacimiento", imp: "800 € (1.º), 1.000 € (2.º), 1.200 € (3.º), 1.400 € (4.º y siguientes)", lim: "No puede generar cuota líquida negativa (salvo abono anticipado)", renta: "BI ≤ 52.800 / 84.480 €; por encima, el 50 % de la deducción", req: "Residencia fiscal en IB el ejercicio anterior; incompatible con ayudas de la CAIB por nacimiento", art: "6 ter" },
      { n: "Adopción", imp: "800 € (1.º), 1.000 € (2.º), 1.200 € (3.º), 1.400 € (4.º y siguientes)", lim: "No puede generar cuota líquida negativa", renta: "BI ≤ 33.000 / 52.800 €", req: "Solo el periodo de inscripción en el Registro Civil; no si se adopta al hijo del cónyuge", art: "6 quater" },
      { n: "Gastos de personas mayores de 65 años o con discapacidad", imp: "40 %", lim: "660 €", renta: "BI ≤ 33.000 / 52.800 €", req: "Residencias, centros de día, custodia, comedor o cuidador; incompatible con art. 6 bis", art: "6 quinquies" },
      { n: "Gastos derivados de la ELA", imp: "100 %", lim: "3.500 €", renta: "BI ≤ 52.800 / 84.480 €", req: "Del contribuyente o de ascendientes/descendientes a cargo; facturas", art: "6 sexties" },
      { n: "Inversión en entidades nuevas o de reciente creación", imp: "30 % (50 % si participadas por centros de investigación o universidades)", lim: "6.000 €/ejercicio (12.000 € en el 50 %)", renta: "No se fija", req: "≤40 % del capital; domicilio en IB; actividad (no arrendamiento); 1 empleado; cifra de negocio ≤2 M€; mantener 4 años", art: "7" },
      { n: "Fomento de la autoocupación", imp: "1.000 €", lim: "—", renta: "BI ≤ 33.000 / 52.800 €", req: "Primera alta en el Censo de Empresarios; actividad en IB; permanencia ≥1 año", art: "7 bis" },
      { n: "Ocupación de puestos de trabajo de difícil cobertura", imp: "40 % de gastos de vivienda en IB o de transporte interinsular", lim: "2.000 € (BI ≤33.000/52.800 €) o 1.000 € (BI ≤52.800/84.480 €)", renta: "Dos tramos: ≤33.000/52.800 € y ≤52.800/84.480 €", req: "Percibir el complemento de difícil cobertura (o destino de Policía Nacional/Guardia Civil en IB)", art: "7 ter" }
    ]
  },

  cantabria: {
    norma: "Decreto Legislativo 62/2008 (TR Medidas Fiscales en tributos cedidos)",
    id: "BOCT-c-2008-90028",
    url: "https://www.boe.es/buscar/act.php?id=BOCT-c-2008-90028",
    act: "30/04/2026",
    nota: "Todas están en el art. 2. El parámetro de renta es la base liquidable después de las reducciones por mínimo personal y familiar.",
    items: [
      { n: "Arrendamiento de vivienda habitual", imp: "10 %", lim: "300 €/año (600 € en conjunta)", renta: "No se establece en la redacción vigente", req: "Menor de 36 años, o <40 con dos o más hijos, o ≥65 (exonerado si discapacidad ≥65 %); alquiler >10 % de la renta; pago no en efectivo", art: "2.1" },
      { n: "Cuidado de familiares", imp: "100 € por familiar", lim: "—", renta: "No se fija para el contribuyente", req: "Descendiente <3 años, ascendiente >70, o familiar con discapacidad ≥65 %; convivencia >183 días; rentas del familiar ≤6.000 €", art: "2.2" },
      { n: "Obras de mejora en viviendas", imp: "15 %", lim: "1.000 € individual / 1.500 € conjunta (+500 € por discapacidad ≥65 %)", renta: "No se fija", req: "Vivienda propia en Cantabria; rehabilitación, eficiencia, accesibilidad o renovables; pago no en efectivo", art: "2.3" },
      { n: "Donativos a fundaciones, Fondo Cantabria Coopera y asociaciones de discapacidad", imp: "15 % (12 % al Fondo Cantabria Coopera)", lim: "Base conjunta con las estatales ≤10 % de la base liquidable", renta: "No se fija", req: "Fundaciones inscritas con cuentas depositadas", art: "2.4" },
      { n: "Acogimiento familiar de menores", imp: "240 € (o 240 € × número máximo de menores simultáneos)", lim: "1.200 €", renta: "No se fija", req: "Selección previa por entidad pública; sin parentesco y sin adoptar en el periodo", art: "2.5" },
      { n: "Inversión en entidades nuevas o de reciente creación", imp: "15 %", lim: "1.000 €/año", renta: "No se fija", req: "PYME con domicilio en Cantabria; participación familiar ≤40 %; mantener 3 años; 1 empleado residente", art: "2.6" },
      { n: "Gastos de enfermedad", imp: "10 % de honorarios sanitarios; 20 % enfermedades raras; 50 % gastos de ELA", lim: "500 / 700 € (+100 € con discapacidad ≥65 %); 1.000 / 1.200 €; 2.000 €", renta: "Base liquidable tras mínimos < 22.946 / 31.485 € (tramos del 10 % y 20 %)", req: "Gastos no cubiertos por la SS ni aseguradora; factura y pago no en efectivo", art: "2.7" },
      { n: "Gastos de guardería", imp: "15 %", lim: "300 €/año por hijo <3 años", renta: "No se fija", req: "Hijos biológicos o adoptados; factura y pago no en efectivo", art: "2.8" },
      { n: "Familias monoparentales", imp: "200 €/año", lim: "—", renta: "Base liquidable tras mínimos < 31.485 €", req: "Padre o madre con hijos menores, o mayores incapacitados judicialmente", art: "2.9" },
      { n: "Nacimiento o adopción de hijos", imp: "1.400 € (1.600 € si discapacidad ≥33 %), el ejercicio y los 2 siguientes", lim: "—", renta: "No se fija", req: "Nacimientos y adopciones desde 1-1-2024; prorrateo por mitad; compatible con la estatal", art: "2.10" },
      { n: "Municipios en riesgo de despoblamiento: arrendamiento", imp: "20 %", lim: "600 € individual / 1.200 € conjunta", renta: "No se fija", req: "Vivienda en municipio en riesgo; incompatible con el art. 2.1", art: "2.11.1" },
      { n: "Municipios en riesgo: guardería", imp: "30 %", lim: "600 €/año por hijo <3 años", renta: "No se fija", req: "Vivienda habitual en municipio en riesgo; incompatible con el art. 2.8", art: "2.11.2" },
      { n: "Municipios en riesgo: traslado por motivos laborales", imp: "500 € (el ejercicio del traslado y el siguiente)", lim: "Parte autonómica de la cuota de trabajo y actividades", renta: "No se fija", req: "Traslado por actividad laboral y permanencia el año del traslado y los 3 siguientes", art: "2.11.3" },
      { n: "Municipios en riesgo: gastos de traslado por estudios", imp: "200 € por hijo", lim: "—", renta: "Hijo estudiante con rentas <8.000 €", req: "Menor de 25 años que curse bachillerato, FP o universidad fuera del municipio", art: "2.11.4" },
      { n: "Residencia habitual en municipio en riesgo de despoblamiento", imp: "20 % de la cuota íntegra autonómica", lim: "500 €", renta: "No se fija", req: "Menor de 40 años con residencia todo el año natural en el municipio", art: "2.11.5" },
      { n: "Inversiones o donaciones a entidades de Economía Social", imp: "20 % (aportaciones de socio); 50 % (donaciones para actividades económicas); 25 % (donaciones de fomento)", lim: "Límite conjunto 3.000 €", renta: "No se fija", req: "Entidad de economía social inscrita con domicilio en Cantabria y 1 empleado; mantener 3 años (5 la participación)", art: "2.12" },
      { n: "Gastos de educación (libros de texto e idiomas)", imp: "100 % de libros de enseñanzas obligatorias y 15 % de enseñanza extraescolar de idiomas", lim: "Suma de ambas ≤200 € por unidad familiar", renta: "No se fija", req: "Hijos en enseñanza obligatoria; factura y pago no en efectivo", art: "2.13 (2.º)" },
      { n: "Ayuda doméstica", imp: "20 % de la cotización anual del empleado de hogar", lim: "300 €", renta: "No se fija", req: "Afiliación en Cantabria y estar en uno de los tres supuestos (hijos menores, ≥75 años o convivencia con discapacidad ≥65 %)", art: "2.14" },
      { n: "Inversiones de nuevos contribuyentes procedentes del extranjero", imp: "20 % del valor de adquisición", lim: "Aplicable el ejercicio y los 5 siguientes", renta: "No se fija", req: "Inmuebles en Cantabria no destinados a vivienda, o valores de entidades con domicilio en Cantabria; no residente los 5 años previos; mantener 6 años", art: "2.15" },
      { n: "Gastos de desplazamiento y permanencia de nuevos residentes", imp: "10 % (25 % si el traslado es por motivos laborales)", lim: "1.000 €/año (1.500 € por motivos laborales)", renta: "No se fija", req: "No haber residido en Cantabria los 4 años anteriores y mantener la residencia 3 años", art: "2.16" },
      { n: "Arrendamiento de viviendas vacías", imp: "500 € por inmueble", lim: "Máximo 3 viviendas", renta: "No se fija", req: "Vacía al menos el año anterior; contrato ≥3 años; arrendatario no pariente ≤3.er grado; alquiler ≤1.000 €/mes", art: "2.17" },
      { n: "Fomento del ejercicio físico y la práctica deportiva", imp: "30 %", lim: "150 €/año", renta: "Base liquidable tras mínimos < 22.946 / 31.485 €", req: "Gimnasios, entidades del Registro del Deporte de Cantabria, clases o licencias; servicios prestados en Cantabria; factura", art: "2.18" },
      { n: "Adquisición o rehabilitación de vivienda habitual para menores de 36 años", imp: "15 % (adquisición) y 15 % (cuenta vivienda)", lim: "Base máx. 9.000 €/año y 6.000 €/año respectivamente", renta: "Base liquidable tras mínimos < 22.946 / 31.485 €", req: "Menor de 36 años; vivienda en Cantabria; el ejercicio de la adquisición y los 2 siguientes", art: "2.19" },
      { n: "Compromiso medioambiental", imp: "Hasta 100 €", lim: "Importe de la tasa municipal de residuos, máx. 100 €", renta: "No se fija", req: "Pagar la tasa de residuos de la vivienda habitual y certificado de participación en actuaciones medioambientales", art: "2.20" }
    ]
  },

  aragon: {
    norma: "Decreto Legislativo 1/2005 (TR tributos cedidos)",
    id: "BOA-d-2005-90006",
    url: "https://www.boe.es/buscar/act.php?id=BOA-d-2005-90006",
    act: "07/07/2025",
    nota: "El texto consolidado del BOE tiene fecha 07/07/2025: puede no incorporar modificaciones autonómicas posteriores. Verificar en el portal de la DGA.",
    items: [
      { n: "Nacimiento o adopción del tercer hijo o sucesivos", imp: "500 € (600 € si se cumple el límite de renta)", lim: "—", renta: "Para 600 €: BI menos mínimos ≤ 21.000 / 35.000 €", req: "Solo el periodo del nacimiento; prorrateo por partes iguales", art: "110-2" },
      { n: "Grado de discapacidad de alguno de los hijos", imp: "200 €", lim: "—", renta: "No se fija", req: "Hijo con discapacidad ≥33 % a fecha de devengo; compatible con el art. 110-2", art: "110-3" },
      { n: "Adopción internacional de niños", imp: "600 € por hijo", lim: "—", renta: "No se fija", req: "Periodo de la resolución judicial; compatible con arts. 110-2, 110-3 y 110-16", art: "110-4" },
      { n: "Cuidado de personas dependientes", imp: "150 €", lim: "—", renta: "BI menos mínimos ≤ 21.000 / 35.000 €", req: "Ascendiente >75 años o familiar con discapacidad ≥65 %; convivencia ≥ mitad del periodo; rentas ≤8.000 €", art: "110-5" },
      { n: "Donaciones con finalidad ecológica y de investigación científica y técnica", imp: "20 %", lim: "10 % de la cuota íntegra autonómica", renta: "No se fija", req: "A la CA de Aragón o entidades sin fin lucrativo inscritas con ese fin", art: "110-6" },
      { n: "Adquisición de vivienda habitual por víctimas del terrorismo", imp: "3 %", lim: "Base y límite estatales vigentes a 31-12-2012", renta: "No se fija (sí comprobación patrimonial)", req: "Vivienda nueva en Aragón acogida a protección pública; primera residencia habitual", art: "110-7" },
      { n: "Inversión en acciones del segmento de empresas en expansión del MAB", imp: "20 %", lim: "10.000 €", renta: "No se fija", req: "≤10 % del capital; mantener 2 años; domicilio en Aragón; incompatible con art. 110-9", art: "110-8" },
      { n: "Inversión en entidades nuevas o de reciente creación", imp: "20 %", lim: "4.000 €", renta: "No se fija", req: "Solo sobre el exceso de la base máxima estatal; domicilio en Aragón; sin funciones ejecutivas; incompatible con art. 110-8", art: "110-9" },
      { n: "Adquisición o rehabilitación de vivienda habitual en núcleos rurales", imp: "5 %", lim: "Base y límite estatales vigentes a 31-12-2012", renta: "BI menos mínimos ≤ 21.000 / 35.000 €", req: "Menor de 36 años; primera vivienda; municipio aragonés <3.000 hab. o entidad local menor", art: "110-10" },
      { n: "Adquisición de libros de texto y material escolar", imp: "Conjunta: 100 / 50 / 37,50 € por descendiente según tramos (familia numerosa 150 € fijos). Individual: 50 / 37,50 / 25 € (familia numerosa 75 €)", lim: "Esas cuantías por descendiente", renta: "BI ≤ 12.500 / 25.000 €; familia numerosa ≤ 30.000 / 40.000 €", req: "Primaria y ESO; minorar becas; factura", art: "110-11" },
      { n: "Arrendamiento de vivienda habitual vinculado a dación en pago", imp: "10 %", lim: "Base máx. 4.800 €/año", renta: "BI ≤ 15.000 / 25.000 €", req: "Vinculado a las daciones en pago del art. 121-10; fianza depositada", art: "110-12" },
      { n: "Arrendamiento de vivienda social", imp: "30 %", lim: "Base: cuota autonómica de los rendimientos de esas viviendas", renta: "No se fija", req: "Poner viviendas a disposición de la Administración de Aragón o del Plan de Vivienda Social", art: "110-13" },
      { n: "Mayores de 70 años", imp: "75 €", lim: "—", renta: "BI ≤ 23.000 / 35.000 €", req: "70 o más años y rendimientos de la base general que no procedan solo del capital", art: "110-14" },
      { n: "Nacimiento o adopción del primer y/o segundo hijo", imp: "100 € (1.º) y 150 € (2.º); 200 € y 300 € si se cumple el límite de renta", lim: "—", renta: "Para los importes incrementados: BI ≤ 23.000 / 35.000 €", req: "Residir el año del nacimiento y el anterior en municipios <10.000 hab.; incompatible con art. 110-3", art: "110-16" },
      { n: "Gastos de guardería de hijos menores de 3 años", imp: "15 %", lim: "250 € por hijo (125 € el año en que cumple 3)", renta: "Base liquidable < 35.000 / 50.000 € y base del ahorro ≤4.000 €", req: "Guardería o centro autorizado; descendientes con derecho al mínimo", art: "110-17" },
      { n: "Inversión en entidades de la economía social", imp: "20 %", lim: "4.000 €", renta: "No se fija", req: "Entidad de economía social con domicilio en Aragón y 1 empleado; mantener 5 años; ≤40 %", art: "110-19" },
      { n: "Adquisición de abonos de transporte público", imp: "Importe de los gastos", lim: "50 €", renta: "No se fija", req: "Abonos unipersonales y nominales, incluidas cuotas de bicicleta pública; aplicable tras su reglamento", art: "110-20" },
      { n: "Gastos en clases de apoyo o refuerzo", imp: "25 %", lim: "Hasta 300 € (familia numerosa) o 200 / 100 / 80 € por tramos", renta: "Tramos de BI: familia numerosa ≤30.000/40.000 €; resto ≤12.500/25.000 €", req: "Clases extraescolares de Infantil, Básica Obligatoria y FP Básica; minorar ayudas; factura", art: "110-21" },
      { n: "Formación para la autonomía y vida independiente de menores con discapacidad", imp: "25 %", lim: "Mismos tramos y máximos que el art. 110-21", renta: "Mismos tramos que el art. 110-21", req: "Descendientes menores de edad con discapacidad ≥65 %; minorar ayudas; factura", art: "110-22" }
    ]
  },

  clm: {
    norma: "Ley 8/2013 (Medidas Tributarias de Castilla-La Mancha)",
    id: "BOE-A-2014-1094",
    url: "https://www.boe.es/buscar/act.php?id=BOE-A-2014-1094",
    act: "31/12/2025",
    nota: "Límite general (art. 15): suma de bases imponibles general y del ahorro menos el mínimo por descendientes ≤ 27.000 € individual / 36.000 € conjunta, salvo que la deducción indique otro.",
    items: [
      { n: "Nacimiento o adopción de hijos", imp: "100 € (1.º), 500 € (2.º), 900 € (3.º y sucesivos); se duplica con discapacidad ≥65 %", lim: "—", renta: "Límite general (27.000 / 36.000 €)", req: "Convivencia; prorrateo al 50 %; solo el periodo del nacimiento o adopción", art: "1" },
      { n: "Discapacidad del contribuyente", imp: "300 €", lim: "—", renta: "Límite general", req: "Discapacidad acreditada ≥65 %", art: "2" },
      { n: "Discapacidad de ascendientes o descendientes", imp: "300 € por persona", lim: "—", renta: "Límite general", req: "Discapacidad ≥65 %; derecho al mínimo por ese familiar", art: "3" },
      { n: "Contribuyentes mayores de 75 años", imp: "150 €", lim: "—", renta: "Límite general", req: "No aplicable si el contribuyente reside en residencia pública o concertada", art: "4" },
      { n: "Cuidado de ascendientes mayores de 75 años", imp: "150 € por ascendiente", lim: "—", renta: "Límite general", req: "Convivencia ≥183 días; ascendiente sin rentas >8.000 €", art: "5" },
      { n: "Acogimiento familiar no remunerado de menores", imp: "500 € (1.er menor) / 600 € (2.º y sucesivos)", lim: "—", renta: "Límite general", req: "Convivencia ≥183 días (prorrateo si es menor); sin ayudas económicas de la Junta", art: "6" },
      { n: "Acogimiento no remunerado de mayores de 65 años o con discapacidad", imp: "600 €", lim: "—", renta: "Límite general", req: "Convivencia ≥183 días; sin parentesco ≤4.º grado; sin ayudas de la Junta", art: "7" },
      { n: "Arrendamiento de vivienda habitual por menores de 36 años", imp: "15 % (20 % en municipios ≤2.500 hab. o entre 2.500 y 10.000 hab. alejados)", lim: "450 € (612 € en el 20 %)", renta: "Suma de bases ≤ 12.500 / 25.000 €", req: "Menor de 36 años; fianza depositada; identificar NIF del arrendador", art: "8" },
      { n: "Gastos en la adquisición de libros de texto y enseñanza de idiomas", imp: "100 % de libros y 15 % de enseñanza de idiomas", lim: "Escala por tramos: 200 / 100 / 75 / 50 / 37,50 / 25 € por hijo (familia numerosa: 200 / 100 €); idiomas 15 € por hijo", renta: "Escalas propias por tramos de base imponible (hasta 40.000 € en familia numerosa)", req: "Educación obligatoria; minorar becas; factura", art: "9" },
      { n: "Discapacidad de cónyuge", imp: "300 €", lim: "—", renta: "Límite general", req: "Cónyuge con discapacidad ≥65 % que no presente declaración individual", art: "10" },
      { n: "Familias numerosas", imp: "200 € (general) / 400 € (especial); 300 € / 900 € si hay discapacidad ≥65 %", lim: "—", renta: "Suma de bases ≤ 27.000 / 36.000 €", req: "Título vigente; incompatible con la de nacimiento por el mismo hijo en algunos casos", art: "11" },
      { n: "Gastos por guardería (0-3 años)", imp: "30 %", lim: "500 € por hijo", renta: "Suma de bases ≤ 27.000 / 36.000 €", req: "Ambos progenitores con rendimientos del trabajo o de actividades; factura", art: "12" },
      { n: "Adquisición o rehabilitación de vivienda en municipios en riesgo de despoblación", imp: "15 %", lim: "Base máx. 180.000 €", renta: "No se fija", req: "Municipios ≤5.000 hab. o zonas escasamente pobladas; residencia efectiva 3 años", art: "13" },
      { n: "Donativos para la cooperación internacional al desarrollo y a entidades sin ánimo de lucro", imp: "15 %", lim: "10 % de la cuota íntegra autonómica", renta: "No se fija", req: "Entidades inscritas en los registros de la Junta", art: "14" },
      { n: "Donaciones con finalidad en investigación y desarrollo científico e innovación", imp: "15 %", lim: "10 % de la cuota íntegra autonómica", renta: "No se fija", req: "A la Junta, universidades públicas o centros de investigación de CLM", art: "14 bis" },
      { n: "Donaciones de bienes culturales y para la conservación del patrimonio", imp: "15 %", lim: "10 % de la cuota íntegra autonómica", renta: "No se fija", req: "Bienes del Patrimonio Cultural de CLM inscritos", art: "14 ter" }
    ]
  },

  extremadura: {
    norma: "Decreto Legislativo 1/2018 (TR disposiciones legales en tributos cedidos)",
    id: "DOE-c-2018-90003",
    url: "https://www.boe.es/buscar/act.php?id=DOE-c-2018-90003",
    act: "31/12/2025",
    items: [
      { n: "Adquisición o rehabilitación de vivienda habitual para jóvenes y víctimas del terrorismo", imp: "3 % (5 % si municipio <3.000 hab.)", lim: "Base máx. 9.040 €/año", renta: "Suma de bases ≤ 28.000 / 45.000 €", req: "Menores de 36 años, o víctimas del terrorismo, o discapacidad ≥65 %; vivienda nueva o rehabilitada de protección pública", art: "1" },
      { n: "Arrendamiento de vivienda habitual", imp: "5 % (10 % si municipio <3.000 hab.)", lim: "300 € (400 € en el 10 %)", renta: "Suma de bases ≤ 28.000 / 45.000 €", req: "Menor de 36 años, familia numerosa o discapacidad ≥65 %; sin otra vivienda a <75 km; fianza depositada", art: "2" },
      { n: "Trabajo dependiente", imp: "75 €", lim: "—", renta: "Rendimientos íntegros del trabajo ≤ 12.000 € y resto de rentas ≤300 €", req: "En conjunta, 75 € por cada perceptor que cumpla el requisito", art: "3" },
      { n: "Donaciones al patrimonio histórico y cultural extremeño", imp: "15 % de donaciones puras; 5 % de cantidades para conservación", lim: "Base máx. 300 €", renta: "No se fija", req: "Bienes inscritos en el Inventario del Patrimonio Histórico y Cultural de Extremadura", art: "4" },
      { n: "Cuidado de familiares con discapacidad", imp: "150 € (220 € si el familiar acredita necesidad de tercera persona)", lim: "—", renta: "Suma de bases ≤ 22.000 / 24.000 €; y el familiar sin rentas >el IPREM", req: "Discapacidad ≥65 %; convivencia ≥ mitad del periodo; no aplicable si está en residencia pública", art: "5" },
      { n: "Acogimiento de menores", imp: "250 € (o 300 € si es el segundo o sucesivo menor)", lim: "—", renta: "No se fija", req: "Acogimiento familiar simple, permanente o preadoptivo; ≥183 días (prorrateo si menos)", art: "6" },
      { n: "Partos múltiples", imp: "300 € por hijo", lim: "—", renta: "Suma de bases ≤ 19.000 / 24.000 €", req: "Hijos que convivan y generen el mínimo por descendientes", art: "7" },
      { n: "Gastos de guardería para hijos menores de 4 años", imp: "10 %", lim: "220 €/año", renta: "Suma de bases ≤ 28.000 / 45.000 €", req: "Guarderías o centros autorizados; factura", art: "8" },
      { n: "Adquisición de material escolar", imp: "15 €/hijo", lim: "15 € por hijo", renta: "Suma de bases ≤ 19.000 / 24.000 € (familia numerosa: 24.000 / 30.000 €)", req: "Educación Primaria y ESO; hijos que generen el mínimo", art: "9" },
      { n: "Contribuyentes viudos", imp: "100 € (200 € si tiene a su cargo descendientes que generen el mínimo)", lim: "—", renta: "Suma de bases ≤ 19.000 / 24.000 €", req: "No procede si el contribuyente fue condenado por violencia sobre el cónyuge fallecido", art: "10" },
      { n: "Inversión en adquisición de acciones y participaciones de nuevas entidades", imp: "20 % (25 % en municipios <5.000 hab.)", lim: "4.000 € (6.000 € en el 25 %)", renta: "No se fija", req: "Participación familiar ≤40 %; mantener 3 años; domicilio en Extremadura, actividad y 1 empleado", art: "11" },
      { n: "Autoempleo de jóvenes menores de 36 años y de mujeres", imp: "250 € (300 € si municipio <5.000 hab.)", lim: "—", renta: "No se fija", req: "Primera alta en el censo de empresarios; actividad en Extremadura ≥1 año", art: "12" },
      { n: "Gastos de estudios de descendientes fuera del municipio de residencia", imp: "150 € por descendiente", lim: "—", renta: "Suma de bases ≤ 28.000 / 45.000 €", req: "Estudios universitarios o de FP superior fuera del municipio; descendiente <25 años", art: "13" }
    ]
  },

  murcia: {
    norma: "Decreto Legislativo 1/2010 (TR tributos cedidos)",
    id: "BORM-l-2010-90002",
    url: "https://www.boe.es/buscar/act.php?id=BORM-l-2010-90002",
    act: "30/12/2025",
    nota: "Todas están en el art. 1. «Base imponible» = general + ahorro menos el mínimo personal y familiar, salvo indicación distinta.",
    items: [
      { n: "Inversión en vivienda habitual por jóvenes", imp: "5 %", lim: "Base máx. 9.040 €/año", renta: "Base imponible general < 24.107,20 € y base del ahorro ≤1.800 €", req: "Menores de 35 años; vivienda de nueva construcción", art: "1.Uno" },
      { n: "Donativos para la protección del patrimonio cultural o de promoción cultural y deportiva", imp: "30 %", lim: "10 % de la cuota íntegra autonómica", renta: "No se fija", req: "A la CA de Murcia, entidades locales o entidades sin fin lucrativo del sector", art: "1.Dos" },
      { n: "Gastos de guardería para hijos menores de 3 años", imp: "20 % (30 % en familias numerosas o monoparentales)", lim: "1.000 € por hijo (1.320 € en el 30 %)", renta: "Base imponible ≤ 30.000 / 50.000 €", req: "Ambos progenitores con rendimientos del trabajo o de actividades; guardería autorizada", art: "1.Tres" },
      { n: "Inversión en instalaciones de recursos energéticos renovables", imp: "10 %", lim: "1.000 €/año", renta: "No se fija", req: "Vivienda habitual o proyectos de instalación en la Región de Murcia", art: "1.Cuatro" },
      { n: "Inversión en dispositivos domésticos de ahorro de agua", imp: "20 %", lim: "60 €/año", renta: "No se fija", req: "Dispositivos en la vivienda habitual conforme a la normativa de la CA", art: "1.Cinco" },
      { n: "Adquisición o rehabilitación de segunda vivienda en el interior", imp: "5 %", lim: "300 €/año", renta: "Base imponible general < 24.107,20 € y base del ahorro ≤1.800 €", req: "Municipios del interior determinados por la CA; segunda vivienda", art: "1.Seis" },
      { n: "Inversión en entidades nuevas o de reciente creación", imp: "20 %", lim: "4.000 €/año", renta: "No se fija", req: "Participación familiar ≤40 %; mantener 3 años; domicilio en Murcia, actividad y 1 empleado", art: "1.Siete" },
      { n: "Gastos en material escolar y libros de texto", imp: "120 € por descendiente", lim: "—", renta: "Base imponible ≤ 20.000 / 40.000 €; en familias numerosas, 33.000 / 53.000 €", req: "Educación Primaria, ESO o educación especial; minorar ayudas", art: "1.Ocho" },
      { n: "Acogimiento no remunerado de mayores de 65 años y/o con discapacidad", imp: "600 €", lim: "—", renta: "Base imponible ≤ 30.000 / 50.000 €", req: "Convivencia >183 días; sin parentesco ≤4.º grado; sin contraprestación", art: "1.Nueve" },
      { n: "Donativos para la investigación biosanitaria", imp: "30 %", lim: "10 % de la cuota íntegra autonómica", renta: "No se fija", req: "A la CA, universidades o entidades sin fin lucrativo dedicadas a investigación biosanitaria", art: "1.Diez" },
      { n: "Conciliación (cuotas de empleados de hogar)", imp: "20 % de las cotizaciones", lim: "400 €/año", renta: "No se fija", req: "Hijos menores de 12 años; alta como empleador en el sistema especial de empleados de hogar", art: "1.Once" },
      { n: "Nacimiento o adopción", imp: "100 € (1.º), 200 € (2.º), 300 € (3.º y sucesivos)", lim: "—", renta: "Base imponible ≤ 30.000 / 50.000 €", req: "Convivencia; el periodo del nacimiento y los 2 siguientes; prorrateo", art: "1.Doce" },
      { n: "Adquisición de bicicletas urbanas", imp: "30 %", lim: "150 € por bicicleta", renta: "No se fija", req: "Bicicletas urbanas nuevas de uso particular; máximo una por miembro de la unidad familiar", art: "1.Trece" },
      { n: "Arrendamiento de vivienda habitual", imp: "10 %", lim: "300 €/año (150 € si menor de 40 años en municipio <2.500 hab.)", renta: "Base imponible ≤ 30.000 / 50.000 €", req: "Menor de 40 años (o determinados colectivos); fianza depositada", art: "1.Quince" },
      { n: "Fomento del ejercicio físico y la práctica deportiva", imp: "30 %", lim: "300 €/año", renta: "Base imponible ≤ 30.000 / 50.000 €", req: "Cuotas de gimnasios y entidades deportivas inscritas en Murcia; factura y pago no en efectivo", art: "1.Veintidós" },
      { n: "Gastos en salud mental y bucodental", imp: "30 %", lim: "500 €/año", renta: "Base imponible ≤ 30.000 / 50.000 €", req: "Tratamientos del contribuyente y de quienes generen el mínimo; factura", art: "1.Veintitrés" }
    ]
  },

  larioja: {
    norma: "Ley 10/2017 (consolidación de impuestos propios y tributos cedidos)",
    id: "BOE-A-2017-13750",
    url: "https://www.boe.es/buscar/act.php?id=BOE-A-2017-13750",
    act: "30/12/2025",
    nota: "Todas están en el art. 32. Muchas exigen base liquidable general ≤18.030 € (individual) / 30.050 € (conjunta) y base del ahorro ≤1.800 €.",
    items: [
      { n: "Nacimiento y adopción de hijos", imp: "600 € (1.º), 750 € (2.º), 900 € (3.º y sucesivos); +60 € por hijo en partos múltiples", lim: "—", renta: "No se establece", req: "Convivencia a fecha de devengo; prorrateo por mitad", art: "32.1" },
      { n: "Adquisición, construcción o rehabilitación de vivienda habitual en pequeños municipios", imp: "5 %", lim: "452 € por declaración; base máx. 9.040 €", renta: "No se establece", req: "Municipios del anexo I; adquirida o iniciada desde 1-1-2017", art: "32.2" },
      { n: "Escuelas infantiles o cuidadores (0-3 años) en pequeños municipios", imp: "30 %", lim: "600 € por menor", renta: "BL general ≤ 18.030 / 30.050 € y ahorro ≤ 1.800 €", req: "Ambos progenitores con actividad laboral fuera del domicilio", art: "32.3" },
      { n: "Acogimiento familiar o guarda con fines de adopción", imp: "300 € por menor (150 € si convivencia >90 y <183 días)", lim: "—", renta: "No se establece", req: "Formalizado por órgano de La Rioja; no si hay adopción en el ejercicio", art: "32.4" },
      { n: "Hijos de 0 a 3 años residentes en pequeños municipios", imp: "100 € mensuales por hijo", lim: "—", renta: "No se establece", req: "Residir en municipio del anexo I y mantener la residencia 3 años (devolución con intereses si no)", art: "32.5" },
      { n: "Escuelas infantiles de cualquier municipio de La Rioja (0-3)", imp: "20 % de los gastos no subvencionados", lim: "600 € por hijo", renta: "BL general ≤ 18.030 / 30.050 € y ahorro ≤ 1.800 €", req: "Convivencia y derecho al mínimo por descendientes", art: "32.6" },
      { n: "Adquisición de vehículos eléctricos nuevos", imp: "15 %", lim: "300 € (225 € bicicletas de pedaleo asistido)", renta: "No se establece", req: "Precio ≤50.000 €; no afecto a actividad; un vehículo por periodo", art: "32.7" },
      { n: "Fijación de población ocupada en el medio rural", imp: "1.000 €", lim: "—", renta: "No se establece", req: "Inicio de actividad agraria por cuenta propia y mantenimiento de residencia y actividad", art: "32.8" },
      { n: "Gastos de acceso a Internet para jóvenes emancipados", imp: "30 % (40 % en monoparentales o municipios del anexo I)", lim: "—", renta: "BL general ≤ 18.030 / 30.050 € y ahorro ≤ 1.800 €", req: "Menor de 36 años; contrato a su nombre ≥6 meses; una sola vez por vivienda", art: "32.9" },
      { n: "Suministro de luz y gas para jóvenes emancipados", imp: "15 % (20 % en municipios del anexo I; 25 % en monoparentales)", lim: "—", renta: "BL general ≤ 18.030 / 30.050 € y ahorro ≤ 1.800 €", req: "Menor de 36 años; contrato a su nombre ≥6 meses", art: "32.10" },
      { n: "Inversión en vivienda habitual de jóvenes menores de 36 años", imp: "15 %", lim: "Base máx. 9.000 €/año", renta: "BL general ≤ 18.030 / 30.050 € y ahorro ≤ 1.800 €", req: "Vivienda en La Rioja; exige incremento patrimonial equivalente", art: "32.11" },
      { n: "Arrendamiento de vivienda habitual (menores de 36 años)", imp: "10 % (20 % si el municipio está en el anexo I)", lim: "300 €/año por contrato (400 € en el 20 %)", renta: "BL general ≤ 18.030 / 30.050 € y ahorro ≤ 1.800 €", req: "Vivienda en La Rioja efectivamente ocupada; modelo de ITP-AJD presentado", art: "32.12" },
      { n: "Adquisición de bicicletas de pedaleo no asistido", imp: "15 %", lim: "50 € por vehículo; máx. 2 por unidad familiar", renta: "No se establece", req: "Factura", art: "32.13" },
      { n: "Donaciones en materia de mecenazgo", imp: "15 % (mecenazgo y patrimonio cultural); 20 % (empresas culturales y autores)", lim: "500 €/año por tramo; global 30 % de la cuota íntegra autonómica", renta: "No se establece", req: "Ley 3/2021 de Mecenazgo; incompatibilidades entre tramos", art: "32.14" },
      { n: "Bienes del patrimonio histórico de La Rioja", imp: "15 %", lim: "500 €/año", renta: "No se establece", req: "Bienes de titularidad inscritos en el Registro General; excluidas inversiones empresariales", art: "32.15" },
      { n: "Ejercicio físico y práctica deportiva", imp: "30 % (100 % si >65 años o discapacidad ≥33 %)", lim: "300 €/año", renta: "No se establece", req: "Gimnasios, entidades del Registro del Deporte de La Rioja, clases y licencias; servicios prestados en La Rioja; factura completa", art: "32.17" },
      { n: "Enfermos de ELA", imp: "50 %", lim: "2.000 €/año", renta: "No se establece", req: "Diagnóstico y tratamiento de ELA; factura completa u ordinaria", art: "32.18" },
      { n: "Cuotas a organizaciones profesionales agrarias", imp: "Cantidades abonadas", lim: "100 €/año", renta: "No se establece", req: "Organización constituida al amparo de la Ley 19/1977; certificación", art: "32.19" },
      { n: "Enfermedad celiaca diagnosticada", imp: "250 € por persona", lim: "—", renta: "No se establece", req: "Por cada integrante de la unidad familiar con celiaquía; certificado médico definitivo", art: "32.20" }
    ]
  },

  navarra: {
    norma: "Decreto Foral Legislativo 4/2008 (TR Ley Foral del IRPF)",
    id: "Foral · BON 30/06/2008",
    url: "https://www.lexnavarra.navarra.es/detalle.asp?r=29657",
    act: "Régimen foral (Convenio)",
    nota: "IRPF FORAL propio: no está en el BOE y su estructura difiere del régimen común (los mínimos personales y familiares operan como deducción de cuota). Verificar en el Boletín Oficial de Navarra.",
    items: [
      { n: "Inversión en vivienda habitual", imp: "15 % (18 % con dos o más hijos; 30 % en familia numerosa)", lim: "Base máx. 7.000 €/año; conjunto por vivienda 120.000 €", renta: "Suma de bases < 24.000 € (27.000 € con 1-2 descendientes; 30.000 € con 3 o más o familia numerosa)", req: "Vivienda protegida o en municipios <10.000 hab. sin vivienda protegida; residencia 3 años", art: "62.1" },
      { n: "Alquiler de vivienda", imp: "15 % (20 % si <30 años o unidad familiar del art. 71.1.c)", lim: "1.500 €/año (1.600 € en el 20 %)", renta: "Rentas ≤ 30.000 €", req: "El alquiler debe exceder del 10 % de las rentas del periodo", art: "62.2" },
      { n: "Deducción por trabajo", imp: "1.400 € (rendimientos ≤12.500 €), decreciente hasta 400 € (>50.000 €)", lim: "Escala por rendimiento neto", renta: "Escalonada por rendimientos netos del trabajo", req: "+50 % con discapacidad 33-65 %; +100 % si ≥65 %", art: "62.5" },
      { n: "Cuotas sindicales", imp: "15 %", lim: "Base 600 €/año", renta: "No se establece", req: "Obtener rendimientos del trabajo", art: "62.6" },
      { n: "Cuotas y aportaciones a partidos políticos", imp: "15 %", lim: "Base 600 €/año", renta: "No se establece", req: "Acreditación conforme a la LO 8/2007", art: "62.8" },
      { n: "Deducciones personales y familiares (mínimos como deducción)", imp: "Mínimo personal 1.084 €; por descendientes 483 / 512 / 732 / 981 / 1.111 / 1.286 €; +644 € por menor de 3 años; ascendientes 264 / 585 €; discapacidad 674 / 2.360 €", lim: "—", renta: "Para incrementos por descendientes: rentas ≤ 30.000 €", req: "Convivencia; incluye el 75 % de cotizaciones de empleados de hogar para cuidado", art: "62.9" },
      { n: "Participación de las personas trabajadoras en el capital de la empresa", imp: "15 % (20 % si la adquirente es mujer)", lim: "1.500 € / 2.000 €/año; acumulado 6.000 € / 8.000 €", renta: "No se establece", req: "Participación familiar ≤20 %; acciones de la entidad empleadora o su grupo", art: "62.11" },
      { n: "Inversiones en energías renovables (autoconsumo)", imp: "15 %, hasta un máximo del 30 %", lim: "Según letra a) del artículo", renta: "No se establece", req: "Solo autoconsumo o aisladas de red; excluidas las obligatorias por el CTE", art: "62.12" },
      { n: "Vehículos eléctricos o híbridos enchufables", imp: "30 % (eléctricos) / 5 % (híbridos); 35 % / 10 % si se cumple el límite de renta", lim: "Base por vehículo: 35.000 € (M1/N1); 1.500 € (bici eléctrica)", renta: "Para los porcentajes incrementados: rentas ≤ 30.000 € (60.000 € unidad familiar)", req: "Vehículos nuevos de las categorías de los Reglamentos (UE) 2018/858 y 168/2013", art: "62.13" },
      { n: "Sistemas de recarga de vehículos eléctricos", imp: "15 %", lim: "Base 5.000 € / 25.000 € / 200.000 € según potencia", renta: "No se establece", req: "Sistemas conformes al Reglamento (UE) 2023/1804", art: "62.14" },
      { n: "Arrendamiento para emancipación (cuota diferencial)", imp: "50 % de la renta satisfecha", lim: "280 €/mes", renta: "Rentas ≤ 22.000 € (33.000 € conjuntas con la unidad familiar)", req: "Edad entre 23 y 35 años inclusive", art: "68 quinquies A" },
      { n: "Arrendamiento para acceso a vivienda (cuota diferencial)", imp: "50 % (60 % si es beneficiario del programa de vivienda de integración social)", lim: "340 / 280 / 220 €/mes según ingresos familiares ponderados (indicador SARA)", renta: "Escalonada por veces el SARA", req: "Inscripción en el censo de solicitantes de vivienda protegida o contrato visado", art: "68 quinquies B" },
      { n: "Pensiones de viudedad y de jubilación (cuota diferencial)", imp: "Diferencia negativa entre la pensión y 15.400 €", lim: "—", renta: "Pensión inferior a 15.400 €", req: "Pensiones contributivas, con y sin derecho a complementos por mínimos", art: "68 A) y B)" }
    ]
  },

  cyl: {
    norma: "Decreto Legislativo 1/2013 (TR tributos cedidos), modificado por la Ley 4/2024",
    id: "No consolidado en BOE",
    url: "https://www.tributos.jcyl.es/",
    act: "Verificar en el portal de la Junta",
    nota: "AVISO: el texto refundido de Castilla y León NO está consolidado en el BOE. Los datos siguientes proceden de la Ley 4/2024 (que introdujo o modificó estas deducciones) y NO son la lista completa: hay más deducciones vigentes (familia numerosa, nacimiento, cuidado de hijos, discapacidad, alquiler joven, vivienda rural, donativos…) cuyos importes deben verificarse en el portal tributario de la Junta antes de aplicarlos.",
    items: [
      { n: "Nacimiento o adopción de hijos (importes modificados por la Ley 4/2024)", imp: "Según el art. 4 del TR, con los importes actualizados por la Ley 4/2024", lim: "Verificar", renta: "Verificar en el texto vigente", req: "PENDIENTE DE VERIFICAR el importe exacto en el portal de la Junta", art: "TR art. 4" },
      { n: "Deducciones por vivienda en núcleos rurales y alquiler joven", imp: "Verificar", lim: "Verificar", renta: "Verificar", req: "PENDIENTE DE VERIFICAR: no fue posible leer el texto consolidado", art: "TR arts. 7 y ss." },
      { n: "Familia numerosa, cuidado de hijos y discapacidad", imp: "Verificar", lim: "Verificar", renta: "Verificar", req: "PENDIENTE DE VERIFICAR: no fue posible leer el texto consolidado", art: "TR arts. 5, 6 y ss." }
    ]
  },

  paisvasco: {
    norma: "Normas Forales del IRPF: Bizkaia 13/2013 · Gipuzkoa 3/2014 · Araba 33/2013",
    id: "Foral · por territorio histórico",
    url: "https://www.euskadi.eus/",
    act: "Bizkaia actualizado a 01/01/2026",
    nota: "AVISO: el IRPF vasco es FORAL y distinto en cada territorio histórico (Bizkaia, Gipuzkoa y Araba); no está en el BOE. Se recoge la ESTRUCTURA de deducciones verificada en los índices oficiales, pero los IMPORTES Y LÍMITES NO se han podido verificar y deben consultarse en la Diputación Foral correspondiente. Nota clave: las aportaciones a EPSV NO son deducción de cuota, sino reducción de la base imponible general.",
    items: [
      { n: "Deducciones familiares: por descendientes, ascendientes y anualidades por alimentos", imp: "Verificar en la Norma Foral aplicable", lim: "Verificar", renta: "Verificar", req: "Estructura común a los tres territorios (arts. 79-81)", art: "79-81" },
      { n: "Discapacidad o dependencia", imp: "Verificar", lim: "Verificar", renta: "Verificar", req: "Deducción específica por discapacidad o dependencia", art: "82" },
      { n: "Edad", imp: "Verificar", lim: "Verificar", renta: "Verificar", req: "Deducción por edad del contribuyente", art: "83" },
      { n: "Aportaciones al patrimonio protegido de la persona con discapacidad", imp: "Verificar", lim: "Verificar", renta: "Verificar", req: "—", art: "85" },
      { n: "Alquiler de vivienda habitual", imp: "Verificar", lim: "Verificar", renta: "Verificar", req: "Deducción por alquiler de la vivienda habitual", art: "86" },
      { n: "Adquisición de vivienda habitual", imp: "Verificar", lim: "Verificar", renta: "Verificar", req: "A diferencia del régimen común, sigue vigente en territorio foral", art: "87" },
      { n: "Fomento de actividades económicas: inversiones, participación de trabajadores, empresas nuevas", imp: "Verificar", lim: "Verificar", renta: "Verificar", req: "Incluye inversión en empresas de nueva creación y en microempresas/pymes", art: "88-90" },
      { n: "Mecenazgo y donativos", imp: "Verificar", lim: "Verificar", renta: "Verificar", req: "Actividades de mecenazgo", art: "90-91" },
      { n: "Cuotas a sindicatos y a partidos políticos", imp: "Verificar", lim: "Verificar", renta: "Verificar", req: "—", art: "92-93" }
    ]
  }
};
